### PR TITLE
feat: enable connext testnet

### PR DESCRIPTION
**Pull request by erkarl**
This PR enables connext vector for testnet and makes some preparations for mainnet.

### CODE REVIEW

**Comment by raladev** [comment]
- [ ] i tried to withdraw from one channel to another, amount dissapeared from first channel, but i did not get this amount :(
txid does not exist too :(
https://rinkeby.etherscan.io/tx/0x526247613d320a6a0d981743ccd530f17e1086e6c0d44029d14f7fabda66a0d4

testnet > closechannel eth --amount 5 --destination 0x7bbaa13d73F35Df7A10FcBF9507EAE46E19D5aAd
{
  "transactionIdsList": [
    "0x526247613d320a6a0d981743ccd530f17e1086e6c0d44029d14f7fabda66a0d4"
  ]

Screenshot from 2020-12-10 00-54-11
[testnet_closechannel_connext.log](https://github.com/ExchangeUnion/xud-docker/files/5669042/testnet_closechannel_txid.log)

**Review by raladev — CHANGES_REQUESTED** [review]
above

**Comment by erkarl** [comment]
@raladev should be ready to test again. `bash ~/xud.sh -b feat/connext-testnet`

**Comment by erkarl** [comment]
@raladev I've bumped the `vector_node` to 0.0.37 version (for some reason the testnet router node was already running 0.0.37) and rebuilt the xud image to include higher channel timeout. With a a fresh environment, I was able to connect to the router.

Could please you give this another go? :pray:

**Comment by raladev** [comment]
> Could please you give this another go?

- Swaps works fine

Got the same problem for withdrawal (https://github.com/ExchangeUnion/xud-docker/pull/819#issuecomment-742095768), i tried to withdraw to my wallet and to another channel wallet - in both cases my funds are disappeared

```
Balance:
┌──────────┬───────────────┬───────────────────────────────┬────────────────────────────┐
│ Currency │ Total Balance │ Wallet Balance (Not Tradable) │ Channel Balance (Tradable) │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ BTC      │ 0.01240262    │ 0.0024901                     │ 0.00991252                 │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ ETH      │ 0.085         │ 0                             │ 0.085                      │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ LTC      │ 0             │ 0                             │ 0                          │
└──────────┴───────────────┴───────────────────────────────┴────────────────────────────┘
testnet > walletdeposit ETH
{
  "address": "0x93d74A4a81A8979a1676504560212Aa8e901945F"
}
testnet > closechannel ETH --amount 0.020 --destination 0x93d74A4a81A8979a1676504560212Aa8e901945F
{
  "transactionIdsList": [
    "0xf6161ce0db6468ede79457a4088e4227f58da7348ac4e890f74851955bedf95c"
  ]
}
testnet > getbalance

Balance:
┌──────────┬───────────────┬───────────────────────────────┬────────────────────────────┐
│ Currency │ Total Balance │ Wallet Balance (Not Tradable) │ Channel Balance (Tradable) │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ BTC      │ 0.01240262    │ 0.0024901                     │ 0.00991252                 │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ ETH      │ 0.065         │ 0                             │ 0.065                      │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ LTC      │ 0             │ 0                             │ 0                          │
└──────────┴───────────────┴───────────────────────────────┴────────────────────────────┘
testnet > closechannel ETH --amount 0.020 --destination 0x27A63CFE2d8F1Ae7fe97252178A275b4d91f3057
{
  "transactionIdsList": [
    "0x9ead063d924427c961fbb8c66deed23ba81c1c595d186c5832db5b2b23d06e86"
  ]
}
testnet > getbalance

Balance:
┌──────────┬───────────────┬───────────────────────────────┬────────────────────────────┐
│ Currency │ Total Balance │ Wallet Balance (Not Tradable) │ Channel Balance (Tradable) │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ BTC      │ 0.01240262    │ 0.0024901                     │ 0.00991252                 │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ ETH      │ 0.045         │ 0                             │ 0.045                      │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ LTC      │ 0             │ 0                             │ 0                          │
└──────────┴───────────────┴───────────────────────────────┴────────────────────────────┘
testnet > getbalance

Balance:
┌──────────┬───────────────┬───────────────────────────────┬────────────────────────────┐
│ Currency │ Total Balance │ Wallet Balance (Not Tradable) │ Channel Balance (Tradable) │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ BTC      │ 0.01240262    │ 0.0024901                     │ 0.00991252                 │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ ETH      │ 0.045         │ 0                             │ 0.045                      │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ LTC      │ 0             │ 0                             │ 0                          │
└──────────┴───────────────┴───────────────────────────────┴────────────────────────────┘
testnet > 

```

**Review by raladev — CHANGES_REQUESTED** [review]
above

**Review by raladev — APPROVED** [review]

**Pull request merged**
