### PR TITLE
feat: add Boltz daemon

### PR DESCRIPTION
**Pull request by michael1011**
WIP Boltz integration

TODO:
- [x] allow disabling Boltz in config (depends on #495)
- [x] add easy UX described in https://github.com/ExchangeUnion/xud/issues/1520
- [x] support Litecoin chain (needs ~a couple adjustments in the code and~ LND LTC 0.10.1)

### CODE REVIEW

**Comment by michael1011** [comment]
> FATAL: 2020/06/16 13:08:46 Incompatible Boltz version detected. Minimal supported version is: 2.3.0

LND LTC is incompatible because there is *still* no LND LTC 0.10.1. The BTC daemon doesn't come up because the Boltz backend version on testnet is too old. I'll deploy the latest version later today and update you in the PR.

**Comment by kilrau** [comment]
> LND LTC is incompatible because there is still no LND LTC 0.10.1

@losh11 I know we are very persistent, but we urgently need lndltc 0.10.1! :muscle:

**Comment by michael1011** [comment]
I built a new image locally with the latest commit from https://github.com/boltzexchange/boltz-lnd and updated the testnet instance. Works perfectly fine now:

```testnet > status
┌───────────┬────────────────────────────────────────────────┐
│ SERVICE   │ STATUS                                         │
├───────────┼────────────────────────────────────────────────┤
│ bitcoind  │ Ready (light mode)                             │
├───────────┼────────────────────────────────────────────────┤
│ litecoind │ Ready (light mode)                             │
├───────────┼────────────────────────────────────────────────┤
│ geth      │ Ready (light mode)                             │
├───────────┼────────────────────────────────────────────────┤
│ lndbtc    │ Ready                                          │
├───────────┼────────────────────────────────────────────────┤
│ lndltc    │ Syncing                                        │
├───────────┼────────────────────────────────────────────────┤
│ connext   │ Ready                                          │
├───────────┼────────────────────────────────────────────────┤
│ xud       │ Waiting for channels                           │
├───────────┼────────────────────────────────────────────────┤
│ boltz     │ Ready                                          │
└───────────┴────────────────────────────────────────────────┘
testnet > boltzcli getinfo
{
  "symbol": "BTC",
  "lnd_pubkey": "03cfa6fc14c9a578167a7c38fc69d07ffe38f3f03afb28ad37781b06b87f518667"
}

```

**Comment by kilrau** [comment]
Now I manage to create swaps:

Balance pre-swap
```
┌──────────┬───────────────┬────────────────────────────┬───────────────────────────────┐
│ Currency │ Total Balance │ Channel Balance (Tradable) │ Wallet Balance (Not Tradable) │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ BTC      │ 0.00483313    │ 0.0048095                  │ 0.00002363                    │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
```
Swap:
```
testnet > boltzcli createswap 10000 btc
{
  "id": "8Q0u4B",
  "address": "2Mz9Yy6NKAqZgE6M7G8iPop96b63teQdoeA",
  "expected_amount": 10440,
  "bip21": "bitcoin:2Mz9Yy6NKAqZgE6M7G8iPop96b63teQdoeA?amount=0.0001044&label=Send%20to%20BTC%20lightning"
}
```
Balance post-swap:
```
testnet > getbalance

Balance:
┌──────────┬───────────────┬────────────────────────────┬───────────────────────────────┐
│ Currency │ Total Balance │ Channel Balance (Tradable) │ Wallet Balance (Not Tradable) │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ BTC      │ 0.00483313    │ 0.0048095                  │ 0.00002363                    │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
```

Boltz logs show:
```
INFO : 2020/06/16 14:49:52 Created new Swap 8Q0u4B: {
  "Id": "8Q0u4B",
  "Status": "invoice.set",
  "PrivateKey": "97897c9068ee99237c9e8797bdfa88119573015ab610bf16b470926a7596a790",
  "Preimage": "",
  "RedeemScript": "a91408aca8cc4242c071f76e60e5c7a1be7cb5e3ab458763210316252738ba05c03064f7d8ea7f9abda05f067f9a91c2b407a1711c321500b5e0670311071bb175210290d4b1bb2ab5c5dadb47197ecbf2f54adfa4dbee192887134fc7d5a18cf564c568ac",
  "Invoice": "lntb100u1p0w3hq0pp5expfxl29v9d759xvquwhjtxh42gqlx4c4n7k4axjtkyaqts4qrlsdp92d6kymtpwf5kuefq2dmkzupqveex7mfqgf2yxcqzpgsp56czqdc7c0fju4029myg6pyvd3n7j9wp0rgxzgcwgcs6083vletvq9qy9qsq926cj0xe2vqcrwxelwwk4fzls5jfma9gmd0g6qltse9a6ttjum5sdtcw6saenlk84mp87fhe7v2w5z59anskv5vy54gkmhhgr9cjtpsqpen2m5",
  "Address": "2Mz9Yy6NKAqZgE6M7G8iPop96b63teQdoeA",
  "ExpectedAmount": 10440,
  "TimeoutBlockHeight": 1771281
}
```

- [ ] Looking at it a bit closer (swap is from on-chain -> lightning) it shouldn't have let me create this swap since my lnd on-chain balance was below swap amount. So boltz should add a pre-swap `walletbalance` check for that (reverse swap does a channel balance check: `rpc error: code = Unknown desc = FAILURE_REASON_INSUFFICIENT_BALANCE`)

- [ ] testnet > boltzcli createreverseswap 100000
{
  "id": "mwkNTD"
}
and my balance is correctly deducted immediately and held. `lndbtc-lncli listpayments` lists payment after on-chain lockup tx by boltz is confirmed. But since `lndbtc-lncli walletbalance` doesn't show any incoming transfer until the second tx is confirmed, maybe boltzcli can print some more details of the swap, like lockup and destination address so the user can potentially follow the payments herself.
- [ ] Created a normal swap with valid amount this time, but it looks like it's stuck but I'm not sure why or what's going on, think we have to find a better way to visualize what's happening in the course of a swap:
```
testnet > getbalance

Balance:
┌──────────┬───────────────┬────────────────────────────┬───────────────────────────────┐
│ Currency │ Total Balance │ Channel Balance (Tradable) │ Wallet Balance (Not Tradable) │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ BTC      │ 0.00481599    │ 0.0038095                  │ 0.00100649                    │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ ETH      │ 18.74995634   │ 5                          │ 13.74995634                   │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ LTC      │ 4.9993325     │ 4.899638                   │ 0.0996945                     │
└──────────┴───────────────┴────────────────────────────┴───────────────────────────────┘
testnet > boltzcli createswap 10000
{
  "id": "dYBr0z",
  "address": "2N9tuoU5hqx1ry1t1eqwubGpEMR6w4XC8b2",
  "expected_amount": 10440,
  "bip21": "bitcoin:2N9tuoU5hqx1ry1t1eqwubGpEMR6w4XC8b2?amount=0.0001044&label=Send%20to%20BTC%20lightning"
}
````
boltz logs:
```
INFO : 2020/06/16 15:14:54 Creating Swap for 10000 satoshis
INFO : 2020/06/16 15:14:54 Verified redeem script and address of Swap dYBr0z
INFO : 2020/06/16 15:14:54 Listening to events of Swap dYBr0z
INFO : 2020/06/16 15:14:54 Created new Swap dYBr0z: {
  "Id": "dYBr0z",
  "Status": "invoice.set",
  "PrivateKey": "13263802a24bc0c039d800a6d7da2fe9b508917091508cff88bce6777e67fd55",
  "Preimage": "",
  "RedeemScript": "a91401b4700aa8819faea8ef8ac03900675a6a5c052487632103562cb760cedbf66c82ebfa2ab87af0bf34f0b0abbfc28f127eb1a3bbaf08750d670315071bb1752102ee358dba17a24f02bb5b0b2c4fb1300344056fcde55369e9b47bfa3fbf1fc78068ac",
  "Invoice": "lntb100u1p0w3c0wpp54769e0qmjzafvx0460eyea7ktnxf3zqsj7xlja09xpcs80gmlkssdp92d6kymtpwf5kuefq2dmkzupqveex7mfqgf2yxcqzpgsp502tj0ssu0z887x78wyg9ep3qk2u8gx3wfxk5c6y82hxh2avz6wgs9qy9qsqwdcglq8jkqtsr280gyffxnmdrvvhxvcq2t7p9pfyt4xgw8h2qjh9erjwenuv0gl04rhnr3z0k9qfnqfr54us82uqzv06pujt9xqdapcq9plahc",
  "Address": "2N9tuoU5hqx1ry1t1eqwubGpEMR6w4XC8b2",
  "ExpectedAmount": 10440,
  "TimeoutBlockHeight": 1771285
}
```

Not sure how you plan to throw errors if e.g. an invoice can't be paid. Just in the logs? Ok for now, just something to think about.

**Comment by kilrau** [comment]
`lndbtc-lncli listchannels` (just checking that your lndbtc channel is with `BrassMarble` and has enough inbound liquidity. You are creating a regular swap there, not channel creation swap.

**Comment by michael1011** [comment]
Already figured that out with peartobear
But it's time to implement ExchangeUnion/xud#1520 :upside_down_face:

**Comment by losh11** [comment]
lndltc v0.10.1 has been released: https://github.com/ltcsuite/lnd/releases/tag/v0.10.1-beta

**Comment by michael1011** [comment]
All of my initial todos are done. To use boltz in xud-docker:

```
boltzcli btc
boltzcli ltc
```

The two commands you want to use are:

```
boltzcli <chain> deposit
```

and

```
boltzcli <chain> withdraw
```

Looking forward to some feedback!

**Comment by kilrau** [comment]
https://github.com/ExchangeUnion/xud-docker/pull/532#pullrequestreview-434987898

-> breaking db change, dropping boltz db fixes this

**Comment by michael1011** [comment]
>  my first attempt to do a regular submarine swap failed due a weird invoice amount exceeded issue (looks like the invoice was generated with the wrong amount)

This is actually a backend bug that should be fixed now.

>  another question: refunds are not implemented yet, right. Just wondering what I have to actively do something to get my precious satoshis back

They are. Boltz will automatically refund your sats back to the lnd wallet

>  swapinfo only allows to lookup info by swap id. I think you can just let swapinfo print all pending swaps if no id argument is passed.

`getinfo` returns a list of pending swaps already

Rest sounds good

**Comment by michael1011** [comment]
>  the xud-docker set up should allow for typing deposit btc instead of boltzcli deposit btc as described in ExchangeUnion/xud#1520 (@reliveyy can probably help)

Will be covered by #565

**Comment by raladev** [comment]
- [ ] _Please deposit between  10000 and 10000000 satoshis into 2N22k7LwCu5nm3atFHU4X9jyqTwyBShWzZG in the next ~6.7 hours (block height 1773174)_ msg is not true because if I send 10000 i will got not enough deposit balance because of fee.
Screenshot 2020-06-23 13:30:05
Also my transaction stuck in swap.created state, but log said that it has transaction.mempool status

- [ ] createswap and createchannel commands are broken because of changes in the logic of the deposit command

**Comment by kilrau** [comment]
TODO:
- [ ] update https://docs.exchangeunion.com/start-earning/market-maker-guide#your-first-trade (@kilrau )

**Comment by kilrau** [comment]
One more thing I just noticed:
- [ ] `down` doesn't bring the boltz container down, it should be included in the `down` process

**Comment by michael1011** [comment]
> down doesn't bring the boltz container down, it should be included in the down process

Could you help me with that? @reliveyy

**Comment by kilrau** [comment]
Can be a separate PR:
- [ ] add boltz db to backup daemon

**Comment by raladev** [comment]
- [ ] withdraw form 2 channels leads to Timeout err
Screenshot from 2020-06-25 16-54-41
Screenshot from 2020-06-25 16-54-37
Screenshot from 2020-06-25 17-05-47

**Comment by kilrau** [comment]
- [ ] boltz testnet should use a different port
```
- boltz: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint mainnet_boltz_1 (382a008f353d4539a30cb03db5de849cf94270564a00b4746033481f0885b093): Bind for 0.0.0.0:9003 failed: port is already allocated")
```

**Comment by kilrau** [comment]
Also would you mind rebasing this? Connext is not working on this branch.

**Comment by raladev** [comment]
Full list of unmarked points for now:

- [ ] boltz testnet should use a different port
```
- boltz: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint mainnet_boltz_1 (382a008f353d4539a30cb03db5de849cf94270564a00b4746033481f0885b093): Bind for 0.0.0.0:9003 failed: port is already allocated")
```

Can be a separate PR:
- [ ] add boltz db to backup daemon

One more thing I just noticed:
- [ ] `down` doesn't bring the boltz container down, it should be included in the `down` process

- [ ] update https://docs.exchangeunion.com/start-earning/market-maker-guide#your-first-trade (@kilrau )

- [ ]  handle parse error by help printing

- [ ] Please deposit between 10000 and 10000000 satoshis into 2N22k7LwCu5nm3atFHU4X9jyqTwyBShWzZG in the next ~6.7 hours (block height 1773174) msg is not true because if I send 10000 i will get not enough deposit balance because of fee.
_Solution: increase min amount in message to 20000/200000_ 

- [ ] I really think this should print the help output
```
testnet > boltzcli
Missing chain
```
- [ ] testnet > boltzcli createreverseswap 100000
{
  "id": "mwkNTD"
}
and my balance is correctly deducted immediately and held. `lndbtc-lncli listpayments` lists payment after on-chain lockup tx by boltz is confirmed. But since `lndbtc-lncli walletbalance` doesn't show any incoming transfer until the second tx is confirmed, maybe boltzcli can print some more details of the swap, like lockup and destination address so the user can potentially follow the payments herself.

- [ ] Created a normal swap with valid amount this time, but it looks like it's stuck but I'm not sure why or what's going on, think we have to find a better way to visualize what's happening in the course of a swap:

**Pull request merged**
