### PR TITLE
fix(parity): upgrade parity to enable fast sync

### LINKED ISSUE #96: Upgrade parity to latest beta (or latest geth). Goal: fast sync working
Currrent version: `v2.4.7-stable`, but is already deprecated I think and fast sync is not working properly
Let's upgrade to: `v2.6.0-beta`

### PR DESCRIPTION
**Pull request by reliveyy**
Closes #96

### CODE REVIEW

**Comment by reliveyy** [comment]
> I am a little confused right now: why is there a version specified in the [Dockerfile itself](https://github.com/ExchangeUnion/xud-docker/blob/master/images/parity/Dockerfile#L1) and in the `images/versions` file?

The `version` in Dockerfile acts like default value. I will be rewrote by the `tools/build` script.

**Comment by michael1011** [comment]
@kilrau the Ethereum ecosystem is a mess. I will try running Raiden against my fast synced Parity on ropsten and also benchmark the new version of Geth which contains a bunch of improvements against Parity tonight and ping you tomorrow morning with the results.

**Comment by kilrau** [comment]
Waiting for @michael1011 's feedback.

At @reliveyy please put:

Closes https://github.com/ExchangeUnion/xud-docker/issues/96

next time.

**Comment by kilrau** [comment]
Not needed anymore. Solved by https://github.com/ExchangeUnion/xud-docker/pull/109

**Pull request closed without merging**
