### PR TITLE
fix: small status fixes

### LINKED ISSUE #663: Small `status` fixes
- [ ] `status` shows `Can't connect to Connext node` for several seconds while the connext client is loading:

```
testnet > logs connext
2020-08-12 17:12:44,368 INFO Set uid to user 0 succeeded
2020-08-12 17:12:44,379 INFO supervisord started with pid 1
2020-08-12 17:12:45,383 INFO spawned: 'connext' with pid 7

> @connext/rest-api@7.2.0 start /app
> npm run build && npm run prod


> @connext/rest-api@7.2.0 build /app
> npm run clean:build && npm run compile

2020-08-12 17:12:47,065 INFO success: connext entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

> @connext/rest-api@7.2.0 clean:build /app
> rm -rf ./build


> @connext/rest-api@7.2.0 compile /app
> tsc -p tsconfig.json


> @connext/rest-api@7.2.0 prod /app
> node ./build/src
```
and only switches to `Ready` once connext successfully initialized. This is bad UX, since it indicates something is wrong.

It should print the usual `Waiting for connext to come up...` message in that stage.

- [ ] xud status should be `Ready` as soon minimum one swap client has a channel. At the moment it shows `Waiting for channels` unless **all** clients have channels.

### PR DESCRIPTION
**Pull request by rsercano**
resolves #663

Just fixed showing Ready if one of the swap channels are Ready, on the other hand connext is already showing Starting for socket hang up because xud-docker checks for ECONNREFUSED to show Can't connect to Connext node. But while starting connext, xud shows socket hang up

### CODE REVIEW

**Comment by kilrau** [comment]
Lmk when ready to test, it should address both issues mentioned in #663

**Comment by rsercano** [comment]
Actually this has to be handled on xud side IMHO, because getinfo call from xud returns

`connect ECONNREFUSED 10.0.1.5:5040`

At this point xud-docker can't decide whether this's an actual error or it started to run, what do you think? @reliveyy

**Comment by kilrau** [comment]
`xud` returning `connect ECONNREFUSED 10.0.1.5:5040` should be interpreted as `Waiting for connext to come up...` unless connext container exited. So this logic should be revisited and fixed: https://github.com/ExchangeUnion/xud-docker/blob/master/images/utils/launcher/node/connext.py#L93

**Comment by rsercano** [comment]
Alright if that's what you want, I just wanted to make sure, since `ECONNREFUSED` can be many things, on it.

**Comment by raladev** [comment]
> xud status should be Ready as soon minimum one swap client has a channel. At the moment it shows Waiting for channels unless all clients have channels.
is it should work only for lnd? @rsercano  @kilrau 

`or "has no active channels" in connext_status:` will not work for connext because connext has no "has no active channels" status, status of connect will be "Ready" after connection establishing and as a result xud Status may be ready before lnd channel opening.

**Comment by kilrau** [comment]
> ` "has no active channels" in connext_status:` will not work for connext because connext has no "has no active channels" status, status of connect will be "Ready" after connection establishing and as a result xud Status may be ready before lnd channel opening and before connext channel opening.

True. But I think we should rather fix that up in `xud`, adding a `connext has no active channels` status to connext. I opened an issue: https://github.com/ExchangeUnion/xud/issues/1837 This PR here can prepare for that and just show `Ready` for `xud` in `status` as soon as min. one client is `Ready`.

**Comment by rsercano** [comment]
> > ` "has no active channels" in connext_status:` will not work for connext because connext has no "has no active channels" status, status of connect will be "Ready" after connection establishing and as a result xud Status may be ready before lnd channel opening and before connext channel opening.
> 
> True. But I think we should rather fix that up in `xud`, adding a `connext has no active channels` status to connext. I opened an issue: [ExchangeUnion/xud#1837](https://github.com/ExchangeUnion/xud/issues/1837) This PR here can prepare for that and just show `Ready` for `xud` in `status` as soon as min. one client is `Ready`.

Current changes should be sufficient, don't they?

**Review by raladev — APPROVED** [review]

**Pull request merged**
