### PR TITLE
fix: name collision when running multiple utils containers

### LINKED ISSUE #260: Allow multiple utils containers
If one has xud ctl open elsewhere, the utils container exists (because it holds the shell), or if xud ctl was not exited in a clean way, the utils container might still be up too. This leads to a container name collision error and one cannot get into `xud ctl` anymore unless the utils container is manually stopped via `docker stop`. Happened quite often to me and it's annoying.

How it should be: tell the user that there is still another (or multiple) `xud ctl` session open and ask if the user wants to close existing xud ctl sessions. If yes, docker stop *all* open utils containers and start *one* fresh utils container. If no, open a second, third appending `_2`, `_3` etc. utils container

```
xud@ubuntu:~$ bash ~/xud.sh
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 3
🚀 Launching mainnet environment
🌍 Checking for updates...
All up-to-date.
Found 2 existing xud ctl sessions. Do you want to close these? [Y/n] Y
Stopping mainnet_utils_1
Stopping mainnet_utils_2
Removing mainnet_utils_1
Removing mainnet_utils_2
Starting mainnet_utils_1
```

### PR DESCRIPTION
**Pull request by reliveyy**
This commit adds a number suffix to utils container name. It will auto calculate the number which is the maximum existing number plus one. And there is an interactive question before launching xudctl shell. It will prompt you like:

    Found 2 existing xud ctl sessions. Do you want to close these? [Y/n] Y
    Stopping mainnet_utils_1...
    Stopping mainnet_utils_2...
    Removing mainnet_utils_1...
    Removing mainnet_utils_2...

Closes #260

### CODE REVIEW

**Comment by kilrau** [comment]
Missing:
> tell the user that there is still another (or multiple) xud ctl session open and ask if the user wants to close existing xud ctl sessions. If yes, docker stop all open utils containers and start one fresh utils container. If no, open a second, third appending _2, _3 etc. utils container

**Comment by peartobear** [comment]
Failed to close the container, attesting that removal of the container is already in progress - which was untrue. 

https://paste.ubuntu.com/p/vZCQqc5WvC/

**Comment by reliveyy** [comment]
> Failed to close the container, attesting that removal of the container is already in progress - which was untrue.

Fixed the "Conflict" error.

**Comment by kilrau** [comment]
- when 2 utils containers are running, it only detects one and closes one
- did print an unbound variable error when another utils container of the same network was open, but apart from that opening an additional utils container worked fine

```
$ xud -b fix/multi-utils
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 2
🚀 Launching testnet environment
/dev/fd/63: line 262: testnet_utils_1: unbound variable
🌍 Checking for updates...
All up-to-date.
Found 1 existing xud ctl sessions. Do you want to close these? [Y/n] n
```

**Comment by kilrau** [comment]
Oh actually I think I found the reason why it recognizes only one utils container, it's because the additionally created ones have funny names instead utils_2, utils3 etc

```
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
147c0115de85        exchangeunion/utils:latest__fix-multi-utils     "python -m launcher …"   17 seconds ago      Up 16 seconds                                                              beautiful_chatterjee
d1f0418646a9        exchangeunion/utils:latest__fix-multi-utils     "python -m launcher …"   45 seconds ago      Up 43 seconds                                                              testnet_utils_1
54d9b99a1e52        exchangeunion/utils:latest__fix-multi-utils     "python -m launcher …"   15 minutes ago      Up 15 minutes                                                              jolly_spence
```

**Comment by reliveyy** [comment]
@kilrau Nice catch! I'll enhance the utils container matching rules.

**Pull request merged**
