### PR TITLE
feat: add tor support for testnet & mainnet xud

### LINKED ISSUE #135: xud doesn't get .onion address on testnet, mainnet
I noticed that on Testnet both lnd's successfully get `.onion` addresses, but not `xud`: `03640f9e41cf77349ef29ed84ab02671dfc0a76963b8e84209cdeab4c9639ace0b@0.0.0.0:8885`

On Simnet that works.

`xud.log` doesn't show any `.onion` or `tor` entries for P2P, just for the LNDs. It contains:
`22/08/2019 09:46:17.135 [P2P] verbose: Verified reachability of advertised address: 0.0.0.0:8885`

### PR DESCRIPTION
**Pull request by reliveyy**
Resolves #135

* Add tor support for `xud` image (@erkarl added tor support for `xud-simnet` image previously)
* Separate tor as a single container (lnd and xud will share this tor instance)
* Remove supervisord 

The reason why I removed supervisord is that unexpected lnd launch failure may not be resolved by just restarting lnd. And this infinite restarting inside container will not reveal problems ASAP. Besides supervisord, we can wait before launching lnd until all prerequisites of it to be satisfied.

### CODE REVIEW

**Comment by reliveyy** [comment]
> please also include mainnet

IMO this PR doesn't need to change since mainnet uses the same Docker images of testnet

**Comment by kilrau** [comment]
`testnet` and `mainnet` should be using different docker images.

Reason: we e.g. want to finally test a feature which is on current master on testnet, before we tag a release and update the `mainnet` image.

**Comment by kilrau** [comment]
Needs a rebase

**Comment by kilrau** [comment]
Closing in favor of https://github.com/ExchangeUnion/xud-docker/pull/174

**Pull request closed without merging**
