### PR TITLE
chore(tools): fix git HEAD handling logic

### PR DESCRIPTION
**Pull request by reliveyy**
This PR fixes modified images detection when there are uncommited or unstaged changes in current project workspace.

*(updated)*

**How to test this PR?**

1. Clone this repo
2. Checkout to this PR's branch
3. Make some changes to some images (do NOT `git add` or commit)
4. Run `tools/build` you should see `HEAD`

### CODE REVIEW

**Comment by kilrau** [comment]
So how exactly do we test this? Run this branch, ssh into a container, modify e.g. entrypoint, down, up and then what should happen?

**Comment by reliveyy** [comment]
> So how exactly do we test this? Run this branch, ssh into a container, modify e.g. entrypoint, down, up and then what should happen?

How to test this PR?
1. Clone this repo
2. Checkout to this PR's branch
3. Make some changes to some images (do NOT `git add` or commit)
4. Run tools/build you should see `HEAD`

**Comment by sangaman** [comment]
> Run tools/build you should see HEAD

Where should I see `HEAD`? I followed these steps but am still not sure how to tell if it worked. Thanks.

**Comment by reliveyy** [comment]
> Where should I see `HEAD`?

I made some changes like `RUN echo foo` in images/xud/1.0.0-beta.2/Dockerfile

```
diff --git a/images/xud/1.0.0-beta.2/Dockerfile b/images/xud/1.0.0-beta.2/Dockerfile
index 5a668af..9f1fcfb 100644
--- a/images/xud/1.0.0-beta.2/Dockerfile
+++ b/images/xud/1.0.0-beta.2/Dockerfile
@@ -13,6 +13,7 @@ RUN npm run compile
 RUN npm run compile:seedutil
 RUN npm prune --production
 RUN rm -rf seedutil/go
+RUN echo foo
```

Then I run `tools/build` I can see "HEAD" text in the "Branch fix-tools history"

```
$ tools/build              
Branch fix-tools history:
HEAD: 
- xud/1.0.0-beta.2
80bf159: fix tools git HEAD handling logic
  (None)

Images' unmodified history:
- xud/1.0.0-beta.2: HEAD

Detected modified images:
- xud/1.0.0-beta.2
```

**Pull request merged**
