### PR TITLE
feat: add xud-tor support for testnet and mainnet

### LINKED ISSUE #135: xud doesn't get .onion address on testnet, mainnet
I noticed that on Testnet both lnd's successfully get `.onion` addresses, but not `xud`: `03640f9e41cf77349ef29ed84ab02671dfc0a76963b8e84209cdeab4c9639ace0b@0.0.0.0:8885`

On Simnet that works.

`xud.log` doesn't show any `.onion` or `tor` entries for P2P, just for the LNDs. It contains:
`22/08/2019 09:46:17.135 [P2P] verbose: Verified reachability of advertised address: 0.0.0.0:8885`

### PR DESCRIPTION
**Pull request by ghost**
Closes https://github.com/ExchangeUnion/xud-docker/issues/135. This PR adds tor support for testnet and mainnet xud containers. This is a **breaking change** and requires existing instances to clear the data directory (default: `~/.xud-docker`).

As discussed with @reliveyy this is a replacement PR for https://github.com/ExchangeUnion/xud-docker/pull/141 since we want to keep a separate Tor instance/service per container for privacy reasons.

Compared to the other PR we also keep supervisord to automatically restart lnds if it crashes unexpectedly. This PR also adds automatic restarting to xud as a side effect.

### CODE REVIEW

**Comment by kilrau** [comment]
Can you push images for this @erkarl ?

**Comment by erkarl** [comment]
Should be testable now with:
```
sudo rm -Rf .xud-docker
bash xud.sh -b feat/tor-testnet-mainnet
```

**Comment by kilrau** [comment]
And.. xud has a shiny .onion address - works! Going into some more detailed testing now.

**Review by kilrau — APPROVED** [review]
Needs to resolve conflicts (my docker-compose.yml change) apart from that everything worked like a charme. Ready to merge IMO.

**Comment by erkarl** [comment]
Updated @kilrau

**Pull request merged**
