### PR TITLE
chore: update GETH to v1.9.10

### PR DESCRIPTION
**Pull request by michael1011**
Obligatory GETH update PR

Testing instructions:
 
* `bash xud.sh -b update-geth-1910`
* test if raiden and swaps still work

### CODE REVIEW

**Comment by fagunbhavsar** [comment]
Raiden is broken at this point in time so once it is fixed, testing can be moved further cc: @kilrau @erkarl @reliveyy

**Comment by kilrau** [comment]
Needs arm image.

**Comment by erkarl** [comment]
> Works like a charme (even though I still don't understand how it passes the raiden version check):

Could be that the version check is not actually being used.

**Comment by michael1011** [comment]
Ready to be merged? @kilrau

**Comment by kilrau** [comment]
> Ready to be merged? @kilrau

Yes. Can you also build arm64?

**Comment by michael1011** [comment]
I don't have a straightforward way to do this. Maybe @reliveyy could merge this PR and build all the required images for `master`?

**Comment by fagunbhavsar** [comment]
Raiden is still down. Not sure whether the latest change is being reflected here. Please check the log and screencast at https://www.dropbox.com/sh/fvydbsossj7gqk3/AABjifSv2daiBvHgSXR45e8Ca?dl=0

cc: @kilrau

**Comment by kilrau** [comment]
Raiden's behavior is expected since you created a new environment in a new directory and geth started syncing from scratch. Raiden will only come alive once geth is synced. That geth shows `eth.syncing` false is a confusing geth behavior shortly after bootup. Only after it connected to enough peers it starts syncing. We already have an issue to work around that for our users: https://github.com/ExchangeUnion/xud-docker/issues/238

Also consider using GitHubs
```
cli output
```
feature in future with descriptions of the steps you took. Also allows you to hide certain things, like your mainnet SEED ;)

**Comment by kilrau** [comment]
> Maybe @reliveyy could merge this PR and build all the required images for master?

Agreed? @reliveyy

**Comment by fagunbhavsar** [comment]
Found following issue:

- [ ] On Testnet, I am unable to unlock the wallet as it throws an error while using pre-configured password. 

Steps to reproduce:
1. Launch AWS EC2 instance
2. Download xud.sh script following Installation steps
3. Run "bash xud.sh -b update-geth-1910" & select testnet option
4. Run fresh installation along with password setup
5. Run "Unlock"
6. Enter the password which is configured on step 4
7. Validate error

Expected Result:
Wallet should be unlocked

Actual Result:
It throws an error. "Error: 12 UNIMPLEMENTED: call is not supported by the current state of xud"

Screenshot 2020-02-18 at 5 53 22 PM

- [ ] Not able to run the fresh installation of Mainnet

Steps to reproduce:
1. Launch AWS EC2 instance
2. Download xud.sh script following Installation steps
3. Run "bash xud.sh -b update-geth-1910" & select mainnet option
4. Run fresh installation along with password setup

Expected Result:
1. Once the password is set; setup should be completed successfully

Actual Result:
1. It throws an error about mis-configured swap clients. Please check the screenshot and log

Screenshot 2020-02-18 at 6 10 16 PM

[mainnet.log](https://github.com/ExchangeUnion/xud-docker/files/4219227/mainnet.log)

cc: @kilrau  @reliveyy

**Comment by erkarl** [comment]
@fagunbhavsar can you please try `docker system prune -a` and see if you still get the swap clients are misconfigured error?

**Comment by kilrau** [comment]
Thanks @fagunbhavsar , this definitely shouldn't happen. It looks like this is what is failing is `lndltc` though due to some weird state in the lndltc container and not related to this PR. 

Can you try:
- running master (without `-b update-geth-1910`) and see if it works there? If it fails on master with the same error, the problem is not related to this PR. 
- Could you try `down`ing the environment, `docker system prune -a` and then start again? First on master, then on this branch?

**Comment by fagunbhavsar** [comment]
@kilrau so the 2nd issue - about Mainnet - is not happening anymore (neither the update-geth-1910 branch nor the master); but the unlocking of account is not working on both Testnet and Mainnet and the issue is with Master

**Comment by kilrau** [comment]
Gotcha.

>     * Could you try `down`ing the environment, `docker system prune -a` and then start again? First on master, then on this branch?

Did you try that? (we discovered some issues with our update detection)

**Comment by fagunbhavsar** [comment]
@kilrau The observations I came across - includes both conditions, i.e., under normal circumstance and after running docker system prune -a.

**Comment by kilrau** [comment]
Alright, please open a new issue with some more details and logs. We'll digg into that.

**Pull request merged**
