### PR TITLE
feat: connext v2

### PR DESCRIPTION
**Pull request by ghost**
Steps to test:
1. `docker pull connextproject/vector_node:837bafa1`
2. `bash xud.sh -b feat/connext-vector`

What is currently **not** working:
- automatically pulling `connextproject/vector_node` image
- withdraw/close channel
- deposits for multiple currencies
- manual open channel with funds from signer/onchain address

TODO:
  - [x] TBD: migration process
  - [x] collateralization for order placing
    - [x] collateralization for channel opening (separate PR)
  - [x] docker logs connext not working
  - [x] pull vector_node container automatically
  - [x] swap failed flows for vector (maker not cancelling invoice)
  - [x] open channel from signer address
  - [x] withdraw functionality
  - [x] generate admintoken for each node

### CODE REVIEW

**Comment by raladev** [comment]
DO NOT MERGE

**Comment by kilrau** [comment]
small nit, connext logs via `docker logs` not working:
```
d@raspixud:~$ docker logs -f simnet_connext_1 
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Review by kilrau — CHANGES_REQUESTED** [review]
Strange: on my amd64 machine I wiped connext folder and images for an existing simnet env and started it with the instructions provided - got a 15 ETH channel, all seems to be fine and I can issue orders.

On my arm64 machine however, `connext` shows `Waiting for channel` in `getinfo`, which I suspect is hardcoded since xud can't connect to it:
```
18/11/2020 11:57:12.062 [CONNEXT] error: could not verify connection to connext, retrying in 5000 ms: Error: connect EHOSTUNREACH 10.0.1.5:8000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
```

**Review by raladev — CHANGES_REQUESTED** [review]
- [x] for now there is problem with collateralization, collateral request does not work, as a result i cant place buy order and swap.

**Comment by kilrau** [comment]
> collateral request does not work

can confirm this, only sell orders work because no collateralization

**Comment by raladev** [comment]
- [ ] also it seems that something is wrong with failed swap case

Steps:
1. Set nobalancechecks flag = true
2. place sell 20 ETH order as a maker (channel balance = 15)
3. fill it as a taker

Actual Result:
1. Swap Timeout err
2. pending htlcs for lndbtc
3. a lot of connext errors on maker side because of 404
4. Order in hold state on maker side, but not on taker side

[Screenshot from 2020-11-18 17-38-43](https://user-images.githubusercontent.com/29906866/99545423-6a61f480-29c6-11eb-80bf-f076b38ce04b.png)
[Screenshot from 2020-11-18 17-37-03](https://user-images.githubusercontent.com/29906866/99545431-6b932180-29c6-11eb-8fbf-7703c0287d45.png)
[Screenshot from 2020-11-18 17-34-43](https://user-images.githubusercontent.com/29906866/99545436-6c2bb800-29c6-11eb-9d1c-e5e68d9abe97.png)


Actual result:
1. no route err from connext (no swap timeout by xud)
2. no pending htlcs
3. no repeated connext errors on maker side
4. order is not in hold state on both side

**Comment by erkarl** [comment]
@kilrau @raladev 

Collateralization works for me for 0.01 ETH:
```
19/11/2020 11:03:42.110 [CONNEXT] debug: collateral of 0 for ETH is insufficient for order amount 1000000
19/11/2020 11:03:42.112 [RPC] error: call /xudrpc.Xud/PlaceOrder errored with code 9: channel collateralization in progress, please try again in ~1 minute
19/11/2020 11:03:42.434 [CONNEXT] debug: completed collateral request of 100000000000000000 ETH units
19/11/2020 11:03:57.604 [CONNEXT] debug: new inbound capacity (collateral) for ETH of 10000000
```

```
simnet > buy 0.01 ETH/BTC 0.03
9 FAILED_PRECONDITION: channel collateralization in progress, please try again in ~1 minute
simnet > buy 0.01 ETH/BTC 0.03
matched 0.01 ETH @ 0.02723604 with peer SheriffSolution order d78beb30-2a55-11eb-ac6b-c10519dd9b23, attempting swap...
successfully swapped 0.01 ETH with peer order d78beb30-2a55-11eb-ac6b-c10519dd9b23
simnet >
```

and then from the other side
```
simnet > sell 0.01 ETH/BTC 0.02
matched 0.01 ETH @ 0.02 with peer RiceFat order 2ac49620-2a57-11eb-aef2-d3da88282b55, attempting swap...
successfully swapped 0.01 ETH with peer order 2ac49620-2a57-11eb-aef2-d3da88282b55
```

For bigger amounts (14 ETH) the collateralization does not work:
```
19/11/2020 11:08:56.426 [CONNEXT] debug: collateral of 8000000 for ETH is insufficient for order amount 1400000000
19/11/2020 11:08:56.427 [RPC] error: call /xudrpc.Xud/PlaceOrder errored with code 9: channel collateralization in progress, please try again in ~1 minute
19/11/2020 11:08:56.750 [CONNEXT] debug: completed collateral request of 14700000000000000000 ETH units
```

```
simnet > buy 14 ETH/BTC 0.02
9 FAILED_PRECONDITION: channel collateralization in progress, please try again in ~1 minute
simnet >
```

It looks like the collateralization request is successfully sent to the router-node, but it never collateralizes.

After changing the `router.node.config` collateralization settings it seems to work.
```
19/11/2020 11:16:48.187 [CONNEXT] debug: collateral of 8000000 for ETH is insufficient for order amount 1400000000
19/11/2020 11:16:48.189 [RPC] error: call /xudrpc.Xud/PlaceOrder errored with code 9: channel collateralization in progress, please try again in ~1 minute
19/11/2020 11:16:48.537 [CONNEXT] debug: completed collateral request of 14700000000000000000 ETH units
19/11/2020 11:17:03.718 [CONNEXT] debug: new inbound capacity (collateral) for ETH of 1470000000
```

```
simnet > tradehistory
Trades:
┌───────────────┬──────────┬───────┬─────────────┬────────────────────────────┬───────────┬─────────────────────────┐
│ Execution     │ Price    │ Role  │ Order Id    │ Order Id    (Counterparty) │ Swap Hash │ Executed At             │
├───────────────┼──────────┼───────┼─────────────┼────────────────────────────┼───────────┼─────────────────────────┤
│ Sell 14 ETH   │ 0.02 BTC │ Maker │ 95cc7d20... │ N/A (SheriffSolution)      │ 798c0d... │ 11/19/2020, 11:16:56 AM │
```

**Comment by raladev** [comment]
- [ ] collateralization works for order placing, but does not work for channel opening. (after channel opening we should collateralize for 0.1 ETH)

**Comment by erkarl** [comment]
> collateralization works for order placing, but does not work for channel opening. (after channel opening we should collateralize for 0.1 ETH)

This is a bit tricky because the channel opening event is just the user sending funds to the multisig address (the connext address from `xucli getinfo`). Previously, the channel opening went through the `xucli openchannel` command which also triggered the collateralization.

**Comment by raladev** [comment]
>  docker logs connext
works fine for me
```
native@ubuntu:~$ docker logs -f 1c140d1c14fb
Using SQLite store at /database/store.db
VECTOR_DATABASE_URL: sqlite:///database/store.db
Running database migration

@prisma/cli          : 2.11.0
@prisma/client       : 2.10.0
Current platform     : linux-musl
Query Engine         : query-engine 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/query-engine-linux-musl)
Migration Engine     : migration-engine-cli 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/migration-engine-linux-musl)
Introspection Engine : introspection-core 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/introspection-engine-linux-musl)
Format Binary        : prisma-fmt 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/prisma-fmt-linux-musl)
Studio               : 0.311.0
Preview Features     : connectOrCreate

Prisma schema loaded from schema.prisma
🏋️‍  migrate up

All migrations are already applied
Starting node in prod-mode
fastify not found, proceeding anyway
[1605796816336] INFO	 (156 on connext): Rehydrating persisted node
    node: {
      "index": 0,
      "publicIdentifier": "indra6a5rHwXR2YjkUvqKr6zZ4fVeBTjamdHMJfTp2c2VNFiJLpnu5S"
    }
[1605796816707] INFO	 (156 on connext): Created ChannelSigner
    method: "createNode"
    publicIdentifier: "indra6a5rHwXR2YjkUvqKr6zZ4fVeBTjamdHMJfTp2c2VNFiJLpnu5S"
[1605796816714] INFO	 (156 on connext): Connected VectorChainService
    method: "createNode"
    providers: {
      "1337": "http://35.234.110.95:8545"
    }
```

**Review by kilrau — CHANGES_REQUESTED** [review]
Obvious things I stumpled upon, we probably want to separate these into issues?
- connext version in `getinfo` is `TODO: Not exposed, yet`
- arm64 vector image is still missing (my pi env is down)
- USDT missing
- starting the env throws an [ugly traceback](https://paste.ubuntu.com/p/xf2h64T9Nr/) on existing envs, and a questionable [download percentage print](https://paste.ubuntu.com/p/CPGfQz4s8t/)
- collateralization on channel open still not working for me, but works on entering order

But need to change in this PR:
- [x] buy eth swap always fails with [connext server error](https://paste.ubuntu.com/p/RtmPZHRNVn/) (you can see that the collateralization succeeded before)
- [x] volume/folder should be renamed back to `connext` ([from currently `vector`](https://github.com/ExchangeUnion/xud-docker/pull/770/files#diff-8c34cb6cee3b35f313108798aa6fb898c8fa4aa5b2c37101c74ab60ca4330362R110))

Apart from that `sell eth` works fine:
```
simnet > sell 0.9 eth/btc mkt
matched 0.9 ETH @ 0.0299733 with peer SheriffSolution order 0fe96ba0-3245-11eb-a5d2-0fe5ed881d69, attempting swap...
successfully swapped 0.9 ETH with peer order 0fe96ba0-3245-11eb-a5d2-0fe5ed881d69
```

**Comment by kilrau** [comment]
Actually both sides (buy & sell) are failing for me now:
```
simnet > sell 0.9 eth/btc mkt
matched 0.9 ETH @ 0.02996742 with peer SheriffSolution order 81501220-3246-11eb-a5d2-0fe5ed881d69, attempting swap...
failed to swap 0.9 ETH due to SendPaymentFailure with peer order 81501220-3246-11eb-a5d2-0fe5ed881d69, continuing with matching routine...
no more matches found, 0.9 qty will be discarded
simnet > buy 0.9 eth/btc mkt
matched 0.9 ETH @ 0.03119058 with peer SheriffSolution order 814f75e0-3246-11eb-a5d2-0fe5ed881d69, attempting swap...
failed to swap 0.9 ETH due to UnknownError with peer order 814f75e0-3246-11eb-a5d2-0fe5ed881d69, continuing with matching routine...
no more matches found, 0.9 qty will be discarded
```

connext logs: https://paste.ubuntu.com/p/KxpVDgbrmy/

**Review by kilrau — DISMISSED** [review]
>     * starting the env throws an [ugly traceback](https://paste.ubuntu.com/p/xf2h64T9Nr/) on existing envs, and a questionable [download percentage print](https://paste.ubuntu.com/p/CPGfQz4s8t/)

Ran this again just now: ugly traceback is still there: https://paste.ubuntu.com/p/QMpYGWGNRh/ image pull/download percentage works fine now:
image

Apart from this, swapping works :tada: 
```
simnet > listorders

Trading pair: ETH/BTC
┌────────────────────────────────────────────────┬────────────────────────────────────────────────┐
│ Buy                                            │ Sell                                           │
├───────────────┬─────────────┬──────────────────┼───────────────┬─────────────┬──────────────────┤
│ Quantity      │ Price       │ Alias            │ Quantity      │ Price       │ Alias            │
├───────────────┼─────────────┼──────────────────┼───────────────┼─────────────┼──────────────────┤
│ 14.1075       │ 0.03085334  │ SheriffSolution  │ 14.85         │ 0.03209838  │ SheriffSolution  │
└───────────────┴─────────────┴──────────────────┴───────────────┴─────────────┴──────────────────┘

Trading pair: LTC/BTC
┌────────────────────────────────────────────────┬────────────────────────────────────────────────┐
│ Buy                                            │ Sell                                           │
├───────────────┬─────────────┬──────────────────┼───────────────┬─────────────┬──────────────────┤
│ Quantity      │ Price       │ Alias            │ Quantity      │ Price       │ Alias            │
└───────────────┴─────────────┴──────────────────┴───────────────┴─────────────┴──────────────────┘
simnet > tradinglimits

Trading Limits:
┌──────────┬────────────┬────────────┬──────────────┬───────────────┐
│ Currency │ Max Buy    │ Max Sell   │ Reserved Buy │ Reserved Sell │
├──────────┼────────────┼────────────┼──────────────┼───────────────┤
│ BTC      │ 2.42293353 │ 2.47697597 │ 0            │ 0             │
├──────────┼────────────┼────────────┼──────────────┼───────────────┤
│ ETH      │ 0          │ 15         │ 0            │ 0             │
├──────────┼────────────┼────────────┼──────────────┼───────────────┤
│ LTC      │ 4.899638   │ 4.9        │ 0            │ 0             │
└──────────┴────────────┴────────────┴──────────────┴───────────────┘
simnet > sell 1 eth/btc mkt
matched 1 ETH @ 0.03085334 with peer SheriffSolution order dd48f070-33ee-11eb-8083-79336b005a9f, attempting swap...
successfully swapped 1 ETH with peer order dd48f070-33ee-11eb-8083-79336b005a9f
simnet > tradinglimits

Trading Limits:
┌──────────┬────────────┬────────────┬──────────────┬───────────────┐
│ Currency │ Max Buy    │ Max Sell   │ Reserved Buy │ Reserved Sell │
├──────────┼────────────┼────────────┼──────────────┼───────────────┤
│ BTC      │ 2.39208019 │ 2.50782931 │ 0            │ 0             │
├──────────┼────────────┼────────────┼──────────────┼───────────────┤
│ ETH      │ 1          │ 14         │ 0            │ 0             │
├──────────┼────────────┼────────────┼──────────────┼───────────────┤
│ LTC      │ 4.899638   │ 4.9        │ 0            │ 0             │
└──────────┴────────────┴────────────┴──────────────┴───────────────┘
simnet > buy 2 eth/btc mkt
9 FAILED_PRECONDITION: channel collateralization in progress, please try again in ~1 minute
simnet > tradinglimits

Trading Limits:
┌──────────┬────────────┬────────────┬──────────────┬───────────────┐
│ Currency │ Max Buy    │ Max Sell   │ Reserved Buy │ Reserved Sell │
├──────────┼────────────┼────────────┼──────────────┼───────────────┤
│ BTC      │ 2.39208019 │ 2.50782931 │ 0            │ 0             │
├──────────┼────────────┼────────────┼──────────────┼───────────────┤
│ ETH      │ 2.1        │ 14         │ 0            │ 0             │
├──────────┼────────────┼────────────┼──────────────┼───────────────┤
│ LTC      │ 4.899638   │ 4.9        │ 0            │ 0             │
└──────────┴────────────┴────────────┴──────────────┴───────────────┘
simnet > buy 2 eth/btc mkt
matched 2 ETH @ 0.03212796 with peer SheriffSolution order f2371020-33ee-11eb-8083-79336b005a9f, attempting swap...
successfully swapped 2 ETH with peer order f2371020-33ee-11eb-8083-79336b005a9f
simnet > tradinglimits

Trading Limits:
┌──────────┬────────────┬────────────┬──────────────┬───────────────┐
│ Currency │ Max Buy    │ Max Sell   │ Reserved Buy │ Reserved Sell │
├──────────┼────────────┼────────────┼──────────────┼───────────────┤
│ BTC      │ 2.45633618 │ 2.44357331 │ 0            │ 0             │
├──────────┼────────────┼────────────┼──────────────┼───────────────┤
│ ETH      │ 0.1        │ 16         │ 0            │ 0             │
├──────────┼────────────┼────────────┼──────────────┼───────────────┤
│ LTC      │ 4.899638   │ 4.9        │ 0            │ 0             │
└──────────┴────────────┴────────────┴──────────────┴───────────────┘
```

**Comment by raladev** [comment]
>Ran this again just now: ugly traceback is still there: https://paste.ubuntu.com/p/QMpYGWGNRh/ image pull/download percentage works fine now:

same for me, it appears in case of vector node update.

**Comment by erkarl** [comment]
> Ran this again just now: ugly traceback is still there: https://paste.ubuntu.com/p/QMpYGWGNRh/ image pull/download percentage works fine now:
> image

@reliveyy didn't we fix this with https://github.com/ExchangeUnion/xud-docker/pull/796?

**Comment by kilrau** [comment]
> volume/folder should be renamed back to connext (from currently vector)

Can we do this quick fix? @erkarl

**Review by kilrau — DISMISSED** [review]

**Comment by reliveyy** [comment]
> didn't we fix this with #796?

@erkarl Sorry. It's a missing parameter I left while printing logs.

**Review by raladev — CHANGES_REQUESTED** [review]
- common swap flows works fine but:

- [x] `closechannel eth --destination 0xa36d9059C30D82A537e11155849095ABC75B236d`
and `simnet > closechannel eth --amount 0.000000001 (too small) --destination 0x00dAADB8bb8fb5CA023ef9Aeca98e9e14d963c86` lead to 500 err
 
```
[1606852434830] ERROR	 (208 on connext):
    module: "VectorProtocol"
    method: "lockedOperation"
    variable: "outboundRes"
    error: "value out-of-bounds (argument=null, value=\"-120\", code=INVALID_ARGUMENT, version=abi/5.0.8)"
[1606852435069] ERROR	 (208 on connext):
    message: "value out-of-bounds (argument=null, value=\"-120\", code=INVALID_ARGUMENT, version=abi/5.0.8)"
    stack: "Error: value out-of-bounds (argument=null, value=\"-120\", code=INVALID_ARGUMENT, version=abi/5.0.8)\n    at Object.eval (webpack:///./node_modules/@connext/vector-engine/node_modules/@connext/vector-protocol/dist/update.js?:169:47)\n    at Generator.next (<anonymous>)\n    at fulfilled (webpack:///./node_modules/@connext/vector-engine/node_modules/@connext/vector-protocol/dist/update.js?:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
[1606852435070] INFO	 (208 on connext): request completed

```
- [ ] withdraw call does not work, it is critical because i cant get money from walletbalance (walletdeposit works fine)

```
simnet > withdraw 5  eth 0x00dAADB8bb8fb5CA023ef9Aeca98e9e14d963c86
Error: 2 UNKNOWN: connext returned not found response

```

```
[1606852590767] INFO	 (208 on connext): incoming request
    reqId: 3166
    req: {
      "method": "POST",
      "url": "/onchain-transfer",
      "hostname": "connext:8000",
      "remoteAddress": "10.0.1.5",
      "remotePort": 40222
    }
[1606852590769] INFO	 (208 on connext): Route POST:/onchain-transfer not found
    reqId: 3166
[1606852590769] INFO	 (208 on connext): request completed
    reqId: 3166
    res: {
      "statusCode": 404
    }
    responseTime: 1.6955949999392033
```

- [x] would be good to throw help in addition like we do in other cases
```
simnet > closechannel eth
Error: 3 INVALID_ARGUMENT: destination account for the withdrawal is missing
```

```
simnet > withdraw eth

xucli walletwithdraw <amount> <currency> <destination> [fee]

withdraws on-chain funds from xud

Positionals:
  amount       the amount to withdraw, `all` withdraws everything
                                                             [string] [required]
  currency     the ticker symbol of the currency to withdraw.[string] [required]
  destination  the address to send withdrawn funds to        [string] [required]

Options:
  --help             Show help                                         [boolean]
  --version          Show version number                               [boolean]
  --rpcport, -p      RPC service port                                   [number]
  --rpchost, -h      RPC service hostname                               [string]
  --tlscertpath, -c  Path to the TLS certificate of xud                 [string]
  --json, -j         Display output in json format    [boolean] [default: false]
  --xudir, -x        Data directory for xud                             [string]
  --fee              the fee in satoshis (or equivalent) per byte       [number]

Examples:
  xucli walletwithdraw 0.1 BTC              withdraws 0.1 BTC
  1BitcoinEaterAddressDontSendf59kuE
  xucli walletwithdraw 0.1 BTC              withdraws 0.1 BTC using 20 sats/byte
  1BitcoinEaterAddressDontSendf59kuE 20
  xucli walletwithdraw all BTC              withdraws all BTC
  1BitcoinEaterAddressDontSendf59kuE

Not enough non-option arguments: got 1, need at least 3

```

- [x] lost 1 sat during deposits, but got it back after depositing 5 sat (not sure that it is xud err, so, maybe it was connext)
[Screenshot from 2020-12-01 23-11-07](https://user-images.githubusercontent.com/29906866/100797198-cdc23c80-3432-11eb-9664-6f356778eb88.png)
[Screenshot from 2020-12-01 23-11-59](https://user-images.githubusercontent.com/29906866/100797191-cc910f80-3432-11eb-958b-10ff515b2225.png)


- [x] Problem with swap failed swap handling still exists

Steps: (one of reliable way to trigger swap timeout on simnet)
1. place 40 orders as maker
2. fill them by one order as a taker

Balances before swap:

```
taker:

Balance:
┌──────────┬───────────────┬───────────────────────────────┬────────────────────────────┐
│ Currency │ Total Balance │ Wallet Balance (Not Tradable) │ Channel Balance (Tradable) │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ BTC      │ 2.636         │ 0                             │ 2.636                      │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ ETH      │ 10.00000006   │ 0                             │ 10.00000006                │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ LTC      │ 5             │ 0                             │ 5                          │
└──────────┴───────────────┴───────────────────────────────┴────────────────────────────┘

maker:

Balance:
┌──────────┬───────────────┬───────────────────────────────┬────────────────────────────┐
│ Currency │ Total Balance │ Wallet Balance (Not Tradable) │ Channel Balance (Tradable) │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ BTC      │ 2.36399983    │ 0                             │ 2.36399983                 │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ ETH      │ 19.99999993   │ 5                             │ 14.99999993                │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ LTC      │ 5             │ 0                             │ 5                          │
└──────────┴───────────────┴───────────────────────────────┴────────────────────────────┘
```


Balances after swap:

```
taker:

Balance: + pending channels on lnd side
┌──────────┬───────────────┬───────────────────────────────┬────────────────────────────┐
│ Currency │ Total Balance │ Wallet Balance (Not Tradable) │ Channel Balance (Tradable) │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ BTC      │ 2.63399959    │ 0                             │ 2.63399959                 │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ ETH      │ 11.35000006   │ 0                             │ 11.35000006                │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ LTC      │ 5             │ 0                             │ 5                          │


maker:

Balance:
┌──────────┬───────────────┬───────────────────────────────┬────────────────────────────┐
│ Currency │ Total Balance │ Wallet Balance (Not Tradable) │ Channel Balance (Tradable) │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ BTC      │ 2.36534983    │ 0                             │ 2.36534983                 │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ ETH      │ 17.99999993   │ 5                             │ 12.99999993                │
├──────────┼───────────────┼───────────────────────────────┼────────────────────────────┤
│ LTC      │ 5             │ 0                             │ 5                          │
└──────────┴───────────────┴───────────────────────────────┴────────────────────────────┘
```

1. I placed 40 orders with acummulated amount of ETH = 2 and filled them by one order of maker; but 11 orders (0.65 ETH) were failed with swap timeout err (that was triggered by the maker) -all is fine on this step
[Screenshot from 2020-12-01 23-18-10](https://user-images.githubusercontent.com/29906866/100799397-07487700-3436-11eb-9433-c10e2ebf155f.png)
[Screenshot from 2020-12-01 23-16-47](https://user-images.githubusercontent.com/29906866/100799402-07e10d80-3436-11eb-8370-0246b20c5612.png)
2. 2 ETH was locked on taker side (14.99999993 - 12.99999993 = 2 ETH),  also i got 11.35000006-10.00000006 =1.35 ETH as a maker for 29 successful orders - all is fine on this step too
3. But after marking swap as failed maker did nothing. I spent more them 20 mins after that without any actions but nothing new appeared in xud logs.


Actual result after third point:

1. my 0.65 still locked by connext node, i did not get them back
2. taker's lnd node contains 11 pending htlcs
[Screenshot from 2020-12-01 23-20-24](https://user-images.githubusercontent.com/29906866/100799488-2cd58080-3436-11eb-8fbe-b5fafe73092c.png)
3. maker has 11 orders in hold in orderbook, but for taker they are not in hold
[Screenshot from 2020-12-01 23-33-22](https://user-images.githubusercontent.com/29906866/100799531-45459b00-3436-11eb-83b0-f9bde87976c9.png)
4. Taker throws a lot of errors because of resolve attempts
[Screenshot from 2020-12-01 23-16-47](https://user-images.githubusercontent.com/29906866/100799402-07e10d80-3436-11eb-8370-0246b20c5612.png)
5. taker identifies swap timeout err of maker as unexpected err in xucli
[Screenshot from 2020-12-01 23-18-10](https://user-images.githubusercontent.com/29906866/100799397-07487700-3436-11eb-9433-c10e2ebf155f.png)

Expected result:

1. Swap timeout is triggered by maker (as it was)
2. Maker cancels pending ETH amount
3. after successful cancelling it releases pending htlcs of taker
4. after that maker unholds orders
5. taker identifies swap timeout err of maker as swaptimeout err in xucli



- [x] `TODO: Not exposed, yet` for connext version of getinfo response

**Comment by erkarl** [comment]
@raladev - thanks for testing.

>     * common swap flows works fine but:
> 
>     * [ ]  `closechannel eth --destination 0xa36d9059C30D82A537e11155849095ABC75B236d`
>       and `simnet > closechannel eth --amount 0.000000001 (too small) --destination 0x00dAADB8bb8fb5CA023ef9Aeca98e9e14d963c86` lead to 500 err

We get the 500 error with ugly error message at the moment because the error happens at the contract level. Connext team is in the process of adding protocol validations at which point we can address this issue.

>     * [ ]  withdraw call does not work, it is critical because i cant get money from walletbalance (walletdeposit works fine)
I changed the withdraw ETH alias to `xucli closechannel` since the user shouldn't be depositing to the on-chain wallet balance. Deposits happen to/from channel address.

>     * [ ]  would be good to throw help in addition like we do in other cases
> ```
> simnet > closechannel eth
> Error: 3 INVALID_ARGUMENT: destination account for the withdrawal is missing
> ```
The help is available via `withdraw --help` or `closechannel --help`. I've also added a bit of text to the generic utils-cli `help` command.

>     * [ ]  lost 1 sat during deposits, but got it back after depositing 5 sat (not sure that it is xud err, so, maybe it was connext)
>       [Screenshot from 2020-12-01 23-11-07](https://user-images.githubusercontent.com/29906866/100797198-cdc23c80-3432-11eb-9664-6f356778eb88.png)
>       [Screenshot from 2020-12-01 23-11-59](https://user-images.githubusercontent.com/29906866/100797191-cc910f80-3432-11eb-958b-10ff515b2225.png)

I don't see a loss of funds in these screenshots. Can you elaborate?

>     * [ ]  Problem with swap failed swap handling still exists

Thanks, will look into it.

>     * [ ]  `TODO: Not exposed, yet` for connext version of getinfo response

This is in the pipeline for the Connext team to implement. At the moment we cannot query the version via Connext API.

**Comment by raladev** [comment]
> I changed the withdraw ETH alias to `xucli closechannel` since the user shouldn't be depositing to the on-chain wallet balance. Deposits happen to/from channel address.

But i able to get wallet address using walletbalance command (`walletbalance eth`) and can deposit to it (for example, using closechanel), but there is no way to withdraw from wallet balance (closechannel withdraws from channel wallet, not from on-chain wallet).

So, there is 2 ways:
1. repair walletwithdraw
2. dont return on-chain wallet in `walletdeposit eth` response

> I don't see a loss of funds in these screenshots. Can you elaborate?
1. I deposited 0.00000001 -> it was displayed in getbalance call
2. after that i deposited 10 ETH ->  0.00000001 was missed in getbalance call (balance was equal 10 instead of 10.00000001)
3. after that i deposited 0.00000005 -> 0.00000001 was returned back (balance was equal 10.00000006)

**Comment by erkarl** [comment]
> * after that i deposited 10 ETH ->  0.00000001 was missed in getbalance call (balance was equal 10 instead of 10.00000001)
> 
> * after that i deposited 0.00000005 -> 0.00000001 was returned back (balance was equal 10.00000006)

Think it's a rounding error on xud side.

**Comment by raladev** [comment]
> We get the 500 error with ugly error message at the moment because the error happens at the contract level. Connext team is in the process of adding protocol validations at which point we can address this issue.

but what about withdrawing full amount? connext still does not fandle this case?

**Comment by erkarl** [comment]
> but what about withdrawing full amount? connext still does not handle this case?

Yep, same case. Needs protocol validations from Connext team.

**Review by raladev — DISMISSED** [review]

**Comment by erkarl** [comment]
Removed nodeIdentifer from xud config as it's now being handled internally by xud. https://github.com/ExchangeUnion/xud-docker/pull/770/commits/6f91814739b2c039c0f62134d80f67f1198ecd42

**Review by kilrau — APPROVED** [review]

**Pull request merged**
