### PR TITLE
feat(connext): enable 7.0.0 testnet

### PR DESCRIPTION
**Pull request by erkarl**

### CODE REVIEW

**Comment by erkarl** [comment]
I'm seeing this in connext logs:
```
2020-07-22T19:51:24.294Z [ConnextConnect] Called connect with {
  "nodeUrl": "https://connext.testnet.odex.dev",
  "ethProviderUrl": "http://eth.kilrau.com:52041"
}, and signer using private key
[1595447484301] INFO  (70 on connext): Mnemonic set successfully
2020-07-22T19:51:24.301Z [ConnextConnect] Using given store containing 0 channels
2020-07-22T19:51:24.488Z [NodeApiClient] No messagingUrl provided, using nats://connext.testnet.odex.dev:4222 derived from nodeUrl https://connext.testnet.odex.dev/api
[1595447485209] ERROR (70 on connext): Request failed with status code 404
    Error: Request failed with status code 404
        at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)
        at IncomingMessage.emit (events.js:327:22)
        at endReadableNT (_stream_readable.js:1221:12)
        at processTicksAndRejections (internal/process/task_queues.js:84:21)
[1595447485213] INFO  (70 on connext): request completed
    url: "/connect"
    statusCode: 500
    reqId: 21
```

**Comment by erkarl** [comment]
@reliveyy when I ssh into the `connext` container (`docker exec -it testnet_connext_1`) the `package.json`'s version is `7.0.0.alpha19`, but the current commit in `src.py` is `08a453eac82b4c01ff9e85a7780b2ab89c7e9081` which should result in version `7.0.0` - https://github.com/connext/rest-api-client/commit/08a453eac82b4c01ff9e85a7780b2ab89c7e9081

**Comment by kilrau** [comment]
> @reliveyy when I ssh into the `connext` container (`docker exec -it testnet_connext_1`) the `package.json`'s version is `7.0.0.alpha19`, but the current commit in `src.py` is `08a453eac82b4c01ff9e85a7780b2ab89c7e9081` which should result in version `7.0.0` - [connext/rest-api-client@08a453e](https://github.com/connext/rest-api-client/commit/08a453eac82b4c01ff9e85a7780b2ab89c7e9081)

Same:     "@connext/client": "7.0.0-alpha.19"

**Comment by erkarl** [comment]
I pushed another feature branch to see if it triggers a build with correct connext version: https://github.com/ExchangeUnion/xud-docker/pull/616

**Pull request merged**
