### PR TITLE
feat(connext): upgrade connext:latest to 1.3.6

### PR DESCRIPTION
**Pull request by ghost**
This PR upgrades connext client to 1.3.6 version which includes a fix for estimating gas (prevents openchannel ETH maxamount from getting stuck).

### CODE REVIEW

**Comment by raladev** [comment]
- [ ] still have with the stucking
Screenshot from 2020-09-22 18-15-25
Screenshot from 2020-09-22 18-12-47
Screenshot from 2020-09-22 17-05-25

**Review by raladev — CHANGES_REQUESTED** [review]
Above, I waited ~10 mins, nothing changed in indra logs after this time

**Comment by erkarl** [comment]
Have not been able to reproduce this, yet.
```
Balance:
┌──────────┬───────────────┬────────────────────────────┬───────────────────────────────┐
│ Currency │ Total Balance │ Channel Balance (Tradable) │ Wallet Balance (Not Tradable) │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ BTC      │ 2.49849998    │ 2.49849998                 │ 0                             │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ ETH      │ 59.9989049    │ 44.9989049                 │ 15                            │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ LTC      │ 5             │ 5                          │ 0                             │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ USDT     │ 4015.084144   │ 1015.084144                │ 3000                          │
└──────────┴───────────────┴────────────────────────────┴───────────────────────────────┘
simnet > openchannel ETH 15
Error: 2 UNKNOWN: failed to open ETH channel for 1500000000: Signer address Ether balance 15000000000000000000 is less than required amount 15000210000000000000
simnet > openchannel ETH 14.99979001
Error: 2 UNKNOWN: failed to open ETH channel for 1499979001: Signer address Ether balance 15000000000000000000 is less than required amount 15000000010000000000
simnet > openchannel ETH 14.99979000
{
  "transactionId": "0xf59228d62e671047bdf47a7604d7482d85cb764ec1070d199f5792add95f56cd"
}
```

**Comment by erkarl** [comment]
Also tried with the exact same amounts from your previous run, works:
```
simnet > getbalance

Balance:
┌──────────┬───────────────┬────────────────────────────┬───────────────────────────────┐
│ Currency │ Total Balance │ Channel Balance (Tradable) │ Wallet Balance (Not Tradable) │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ BTC      │ 2.49849998    │ 2.49849998                 │ 0                             │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ ETH      │ 89.9978098    │ 74.9984849                 │ 14.9993249                    │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ LTC      │ 5             │ 5                          │ 0                             │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ USDT     │ 5015.084144   │ 1015.084144                │ 4000                          │
└──────────┴───────────────┴────────────────────────────┴───────────────────────────────┘
simnet > openchannel ETH 14.9991249
Error: 2 UNKNOWN: failed to open ETH channel for 1499912490: Signer address Ether balance 14999324900000000000 is less than required amount 14999334900000000000
simnet > openchannel ETH 14.9991
{
  "transactionId": "0xb41fb47c33ba4b954945b3d516fd28692a57840979e28aa1bc9de10f6e25d5cb"
}
```

**Comment by raladev** [comment]
reproduced again on first try.
@erkarl please try this flow:
1. bash xud.sh -b feat/upgrade-connext-136
2. wait for connext channel opening (ETH+USDT)
3. closechannel ETH
4. closechannel USDT --amount 200
5. closechannel USDT
6. openchannel ETH 14.999116 -> not enough balance err
7. openchannel ETH 14.999114 -> stuck 

Screenshot from 2020-09-23 16-50-06

[utils_output.log](https://github.com/ExchangeUnion/xud-docker/files/5268533/connext_stuck_utils.output.log)

connext_client.log:
```
2020-09-23T13:36:06.940Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 25 ms
[1600868168924] INFO  (70 on connext): received request
    url: "/deposit"
    id: 343
    reqId: 343
[1600868168926] INFO  (70 on connext): Getting client for publicIdentifier: indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se
2020-09-23T13:36:08.927Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x34c2..3d1B","assetId":"0x0000..0000"}
2020-09-23T13:36:08.930Z [CF-GetFreeBalanceState] Before execution complete in 3 ms
2020-09-23T13:36:08.932Z [CF-GetFreeBalanceState] Executed method implementation in 2 ms
2020-09-23T13:36:08.933Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 6 ms
[1600868169897] INFO  (70 on connext): Getting client for publicIdentifier: indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se
2020-09-23T13:36:09.901Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x34c2..3d1B","assetId":"0x0000..0000"}
[1600868169925] INFO  (70 on connext): Getting client for publicIdentifier: indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se
2020-09-23T13:36:09.928Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x34c2..3d1B","assetId":"0x292B..91d4"}
2020-09-23T13:36:09.940Z [CF-GetFreeBalanceState] Before execution complete in 39 ms
2020-09-23T13:36:09.948Z [CF-GetFreeBalanceState] Before execution complete in 20 ms
2020-09-23T13:36:09.957Z [CF-GetFreeBalanceState] Executed method implementation in 14 ms
2020-09-23T13:36:09.964Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 64 ms
2020-09-23T13:36:09.966Z [CF-GetFreeBalanceState] Executed method implementation in 15 ms
2020-09-23T13:36:09.967Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 39 ms
2020-09-23T13:36:10.201Z [DepositController] Deposit started: {"amount":"14999114000000000000"}
2020-09-23T13:36:10.203Z [DepositController] Depositing 14999114000000000000 of 0x0000000000000000000000000000000000000000 into channel
2020-09-23T13:36:10.764Z [DepositController] requestDepositRights started: {"assetId":"0x0000000000000000000000000000000000000000"}
2020-09-23T13:36:10.768Z [CF-GetAppInstances] Executing with params: {"multisigAddress":"0x34c2..3d1B"}
2020-09-23T13:36:10.792Z [CF-GetAppInstances] Before execution complete in 24 ms
2020-09-23T13:36:10.799Z [CF-GetAppInstances] Executed method implementation in 5 ms
2020-09-23T13:36:10.801Z [CF-RpcRouter] Processed chan_getAppInstances method in 33 ms
2020-09-23T13:36:12.296Z [DepositController] Calling propose install
2020-09-23T13:36:12.298Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x34c2..3d1B","assetId":"0x0000..0000"}
2020-09-23T13:36:12.314Z [CF-GetFreeBalanceState] Before execution complete in 16 ms
2020-09-23T13:36:12.334Z [CF-GetFreeBalanceState] Executed method implementation in 19 ms
2020-09-23T13:36:12.336Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 38 ms
2020-09-23T13:36:12.342Z [CF-ProposeInstall] Executing with params: {"abiEncodings":{"stateEncoding":"tuple( tuple( address to, uint256 amount)[2] transfers, address multisigAddress, address assetId, uint256 startingTotalAmountWithdrawn, uint256 startingMultisigBalance)"},"appDefinition":"0xb1A6..C088","initialState":{"transfers":[{"amount":"0","to":"0xD4Df..64DE"},{"amount":"0","to":"0xE223..1BA6"}],"multisigAddress":"0x34c2..3d1B","assetId":"0x0000..0000","startingTotalAmountWithdrawn":"10000000000000000000","startingMultisigBalance":"0"},"initiatorDeposit":"0","initiatorDepositAssetId":"0x0000..0000","multisigAddress":"0x34c2..3d1B","outcomeType":"SINGLE_ASSET_TWO_PARTY_COIN_TRANSFER","responderIdentifier":"indra6WRA..4cBh","responderDeposit":"0","responderDepositAssetId":"0x0000..0000","defaultTimeout":"8640","stateTimeout":"8640"}
2020-09-23T13:36:12.478Z [NodeApiClient] Node responded to indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se.indra6WRA6HQQTDQD1FC3KmdbpePijdcgLTqAdi2xy2Q2HqNeGn4cBh.1337.lock.acquire.0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B request in 135 ms
2020-09-23T13:36:12.479Z [CF-ProposeInstall] Acquired locks 0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B in 137 ms
2020-09-23T13:36:12.482Z [CF-ProposeInstall] Before execution complete in 2 ms
2020-09-23T13:36:12.483Z [CF-ProposeProtocol] [0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B] Initiation started
[1600868172896] INFO  (70 on connext): Getting client for publicIdentifier: indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se
2020-09-23T13:36:12.898Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x34c2..3d1B","assetId":"0x0000..0000"}
2020-09-23T13:36:12.900Z [CF-GetFreeBalanceState] Before execution complete in 2 ms
[1600868172902] INFO  (70 on connext): Getting client for publicIdentifier: indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se
2020-09-23T13:36:12.904Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x34c2..3d1B","assetId":"0x292B..91d4"}
2020-09-23T13:36:12.908Z [CF-GetFreeBalanceState] Executed method implementation in 7 ms
2020-09-23T13:36:12.926Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 28 ms
2020-09-23T13:36:12.931Z [CF-GetFreeBalanceState] Before execution complete in 27 ms
2020-09-23T13:36:12.944Z [CF-GetFreeBalanceState] Executed method implementation in 12 ms
2020-09-23T13:36:12.944Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 40 ms
2020-09-23T13:36:13.678Z [CF-ProposeProtocol] [0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B] Signed set state commitment 0x4ac0442f855ff090350ee7979d8843853e7f209edd3260e85edc3c2822bae011 & conditional transfer commitment 0xb2c95626747f56e159c9547dd100b07d4a5503b4cc98bb259412bd269d545a2b in 4 ms
2020-09-23T13:36:14.142Z [CF-ProposeProtocol] [0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B] Asserted valid responder signature set state commitment in 3 ms
2020-09-23T13:36:14.147Z [CF-ProposeProtocol] [0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B] Asserted valid responder signature on conditional transaction in 2 ms
2020-09-23T13:36:14.181Z [CF-ProposeProtocol] [0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B] Persisted app instance 0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737 in 14 ms
2020-09-23T13:36:14.334Z [NodeApiClient] Node responded to indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se.indra6WRA6HQQTDQD1FC3KmdbpePijdcgLTqAdi2xy2Q2HqNeGn4cBh.1337.lock.release.0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B request in 150 ms
2020-09-23T13:36:14.335Z [CF-ProposeInstall] Acquired locks 0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B in 151 ms
2020-09-23T13:36:14.353Z [CF-InstallProtocol] [0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737] Response started
2020-09-23T13:36:14.371Z [CF-InstallProtocol] [0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737] Validated app 0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737 in 18 ms
2020-09-23T13:36:14.382Z [CF-InstallProtocol] [0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737] Verified initiator's free balance update sig in 10 ms
2020-09-23T13:36:14.408Z [CF-InstallProtocol] [0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737] Persisted app 0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737 in 24 ms
2020-09-23T13:36:14.409Z [CF-InstallProtocol] [0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737] Response finished in 56 ms
2020-09-23T13:36:14.412Z [ConnextListener] runPostInstallTasks for app DepositApp 0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737 started
2020-09-23T13:36:14.413Z [ConnextListener] runPostInstallTasks for app DepositApp 0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737 complete
2020-09-23T13:36:14.413Z [ConnextListener] handleAppProposal for app DepositApp 0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737 completed
2020-09-23T13:36:14.415Z [CF-RequestHandler] Event for install protocol was processed in 64 ms
2020-09-23T13:36:14.641Z [DepositController] Installed app with id: 0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737
2020-09-23T13:36:14.643Z [DepositController] Successfully obtained deposit rights for 0x0000000000000000000000000000000000000000
2020-09-23T13:36:14.645Z [DepositController] Sending deposit transaction to chain
[1600868175898] INFO  (70 on connext): Getting client for publicIdentifier: indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se
2020-09-23T13:36:15.900Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x34c2..3d1B","assetId":"0x0000..0000"}
[1600868175904] INFO  (70 on connext): Getting client for publicIdentifier: indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se
2020-09-23T13:36:15.905Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x34c2..3d1B","assetId":"0x292B..91d4"}
2020-09-23T13:36:15.909Z [CF-GetFreeBalanceState] Before execution complete in 9 ms
2020-09-23T13:36:15.918Z [CF-GetFreeBalanceState] Before execution complete in 13 ms
2020-09-23T13:36:15.924Z [CF-GetFreeBalanceState] Executed method implementation in 9 ms
2020-09-23T13:36:15.925Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 25 ms
2020-09-23T13:36:15.928Z [CF-GetFreeBalanceState] Executed method implementation in 9 ms
2020-09-23T13:36:15.929Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 24 ms
[1600868178895] INFO  (70 on connext): Getting client for publicIdentifier: indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se
2020-09-23T13:36:18.897Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x34c2..3d1B","assetId":"0x292B..91d4"}
[1600868178900] INFO  (70 on connext): Getting client for publicIdentifier: indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se
2020-09-23T13:36:18.901Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x34c2..3d1B","assetId":"0x0000..0000"}
2020-09-23T13:36:18.911Z [CF-GetFreeBalanceState] Before execution complete in 14 ms
2020-09-23T13:36:18.918Z [CF-GetFreeBalanceState] Before execution complete in 17 ms
2020-09-23T13:36:18.929Z [CF-GetFreeBalanceState] Executed method implementation in 16 ms
2020-09-23T13:36:18.931Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 35 ms
2020-09-23T13:36:18.935Z [CF-GetFreeBalanceState] Executed method implementation in 17 ms
```

indra node logs:
```
Sep 23 16:33:24a40c3e467837indra_node2020-09-23T13:33:24.060Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 7 ms
Sep 23 16:33:24a40c3e467837indra_node2020-09-23T13:33:24.062Z [ChannelService] Free balance 0 is less than or equal to upper reclaim bound: 5000000000
Sep 23 16:33:24a40c3e467837indra_node2020-09-23T13:33:24.062Z [ChannelService] Rebalance finished for indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se on chain 1337, assetId: 0x292Ba2F10dbFB8925A209d3AdF09C2D2b1f491d4
Sep 23 16:33:26a40c3e467837indra_node2020-09-23T13:33:26.847Z [OnchainTransactionService] Tx mined, hash: 0xe5cf38fd2bdac355b2af5915054f930c723a00cb497eb5c4d30507207a0f7b37
Sep 23 16:33:26a40c3e467837indra_node2020-09-23T13:33:26.863Z [OnchainTransactionService] Success sending transaction! Tx mined at block 28109 on chain 1337: 0xe5cf38fd2bdac355b2af5915054f930c723a00cb497eb5c4d30507207a0f7b37 in 4129ms
Sep 23 16:36:12a40c3e467837indra_node2020-09-23T13:36:12.411Z [LockService] Acquiring lock for 0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B (TTL: 21000 ms)
Sep 23 16:36:12a40c3e467837indra_node2020-09-23T13:36:12.413Z [LockService] Acquired lock for 0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B (value 8071d04d419ee460cc8b0d96f133781d) after waiting 0 ms
Sep 23 16:36:12a40c3e467837indra_node2020-09-23T13:36:12.415Z [MessagingInterface] Responded to indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se.indra6WRA6HQQTDQD1FC3KmdbpePijdcgLTqAdi2xy2Q2HqNeGn4cBh.1337.lock.acquire.0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B in 4 ms
Sep 23 16:36:13a40c3e467837indra_node2020-09-23T13:36:13.907Z [CF-ProposeProtocol] [0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B] Response started
Sep 23 16:36:13a40c3e467837indra_node2020-09-23T13:36:13.961Z [CF-ProposeProtocol] [0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B] Validated proposal 0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737 in 54 ms
Sep 23 16:36:13a40c3e467837indra_node2020-09-23T13:36:13.978Z [CF-ProposeProtocol] [0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B] Asserted valid signature responder propose in 11 ms
Sep 23 16:36:13a40c3e467837indra_node2020-09-23T13:36:13.989Z [CF-ProposeProtocol] [0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B] Asserted valid initiator signature on conditional transaction in 9 ms
Sep 23 16:36:13a40c3e467837indra_node2020-09-23T13:36:13.994Z [CF-ProposeProtocol] [0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B] Signed initial state responder propose in 4 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.001Z [CF-ProposeProtocol] [0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B] Signed conditional tx commitment in 11 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.059Z [CF-ProposeProtocol] [0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B] Persisted app instance 0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737 in 14 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.061Z [CF-ProposeProtocol] [0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B] Response finished in 154 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.062Z [AppRegistryService] installOrReject for app 0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737 with params {"abiEncodings":{"stateEncoding":"tuple( tuple( address to, uint256 amount)[2] transfers, address multisigAddress, address assetId, uint256 startingTotalAmountWithdrawn, uint256 startingMultisigBalance)"},"appDefinition":"0xb1A61dEc7A2BEB2bDC83D6dBbdDBc6a37EdDC088","initialState":{"transfers":[{"amount":{"_hex":"0x00","_isBigNumber":true},"to":"0xD4Df7812A80af64EA15e6F7800b0D013781b64DE"},{"amount":{"_hex":"0x00","_isBigNumber":true},"to":"0xE223A8135A27733Fed9e4812f443EC15ece31BA6"}],"multisigAddress":"0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B","assetId":"0x0000000000000000000000000000000000000000","startingTotalAmountWithdrawn":{"_hex":"0x8ac7230489e80000","_isBigNumber":true},"startingMultisigBalance":{"_hex":"0x00","_isBigNumber":true}},"initiatorDeposit":{"_hex":"0x00","_isBigNumber":true},"initiatorDepositAssetId":"0x0000000000000000000000000000000000000000","multisigAddress":"0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B","outcomeType":"SINGLE_ASSET_TWO_PARTY_COIN_TRANSFER","responderIdentifier":"indra6WRA6HQQTDQD1FC3KmdbpePijdcgLTqAdi2xy2Q2HqNeGn4cBh","responderDeposit":{"_hex":"0x00","_isBigNumber":true},"responderDepositAssetId":"0x0000000000000000000000000000000000000000","defaultTimeout":{"_hex":"0x21c0","_isBigNumber":true},"stateTimeout":{"_hex":"0x21c0","_isBigNumber":true},"initiatorIdentifier":"indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se"} from indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se started
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.065Z [CF-RequestHandler] Event for propose protocol was processed in 176 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.084Z [CF-Install] Executing with params: {"appIdentityHash":"0xea43..a737","multisigAddress":"0x34c2..3d1B"}
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.086Z [LockService] Waiting on lock for 0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B (locked: 0x34c2..3d1B)
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.253Z [LockService] Releasing lock for 0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B after 1840 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.255Z [LockService] Done releasing lock for 0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.256Z [MessagingInterface] Responded to indra6faJg3VWTydHKfQLuua4QjzGrmxfLtM72mZkev8h8Jku5ti1se.indra6WRA6HQQTDQD1FC3KmdbpePijdcgLTqAdi2xy2Q2HqNeGn4cBh.1337.lock.release.0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B in 3 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.258Z [LockService] Acquired lock for 0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B (value 67620e8936bb4f8721685a5b577c07f0) after waiting 172 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.259Z [CF-Install] Acquired locks 0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B in 175 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.263Z [CF-Install] Before execution complete in 3 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.265Z [CF-InstallProtocol] [0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737] Initiation started
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.271Z [CF-InstallProtocol] [0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737] Validated app 0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737 in 6 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.520Z [CF-InstallProtocol] [0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737] Verified responder's sig on free balance update in 9 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.561Z [CF-InstallProtocol] [0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737] Initiation finished in 296 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.564Z [CF-Install] Executed method implementation in 300 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.565Z [LockService] Releasing lock for 0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B after 479 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.567Z [LockService] Done releasing lock for 0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.568Z [CF-Install] Acquired locks 0x34c263E58A5E29f29Ad0f1c2B6Afe28aB3d33d1B in 3 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.570Z [CF-RpcRouter] Processed chan_install method in 486 ms
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.571Z [AppRegistryService] runPostInstallTasks for app name DepositApp 0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737 started
Sep 23 16:36:14a40c3e467837indra_node2020-09-23T13:36:14.573Z [AppRegistryService] runPostInstallTasks for app DepositApp 0xea43f6ebf684a2f44bf485613805aa88c9b779c0f4ef1a439bb57fd15c5da737 completed
```

**Comment by raladev** [comment]
merged without full gas problem fix

**Review by raladev — APPROVED** [review]

**Pull request merged**
