### PR TITLE
chore: update simnet images

### PR DESCRIPTION
**Pull request by reliveyy**
EDIT: Closes https://github.com/ExchangeUnion/xud-docker/issues/326

### CODE REVIEW

**Comment by michael1011** [comment]
Is this also closing #319 @reliveyy?

**Comment by reliveyy** [comment]
> Is this also closing #319 @reliveyy?

Partially solved for simnet image only.

**Comment by reliveyy** [comment]
Raiden fails to start becuase of geth (35.231.222.142:8546) read timeout.

```
...
  File "/opt/venv/lib/python3.7/site-packages/raiden/blockchain/filters.py", line 126, in _do_get_new_entries
    result = self.web3.eth.getLogs(filter_params)
...
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='35.231.222.142', port=8546): Read timed out. (read timeout=10)
```

**Comment by kilrau** [comment]
PS: raiden starts perfectly fine with the current simnet images:
```
Raiden info:
┌──────────┬────────────────────────────────────────────┐
│ Status   │ Ready                                      │
├──────────┼────────────────────────────────────────────┤
│ Version  │ 0.100.5a1.dev162-2217bcb                   │
├──────────┼────────────────────────────────────────────┤
│ Address  │ 0x2190dD2b994558a00ac7de193856fa48a4213897 │
├──────────┼────────────────────────────────────────────┤
│ Channels │ Active: 2 | Pending: 0 | Closed: 0         │
├──────────┼────────────────────────────────────────────┤
│ Network  │ raiden simnet                              │
└──────────┴────────────────────────────────────────────┘ 
```

**Pull request closed without merging**
