### PR TITLE
feat(arby): add configurable trading pair

### PR DESCRIPTION
**Pull request by ghost**
This commit adds `base-asset` and `quote-asset` configuration options
to arby section of `simnet/testnet/mainnet.conf`.

### CODE REVIEW

**Comment by erkarl** [comment]
Just noticed that it's not creating buy orders for me:
```
2020-08-05 06:27:43.4343 [OpenDEX] trace: Creating BTC/USDT buy order with id 51d45870-dd6c-4ff1-a474-449c31c0ccf5, quantity 0.08923735 and price 11206.0704
2020-08-05 06:27:43.4343 [OpenDEX] trace: Creating BTC/USDT sell order with id 22bb07aa-569f-4964-8720-1bbb1fcf25ad, quantity 0.85667854 and price 12139.9096
2020-08-05 06:27:43.4343 [OpenDEX] trace: Order 22bb07aa-569f-4964-8720-1bbb1fcf25ad created
2020-08-05 06:27:43.4343 [OpenDEX] warn: 9 FAILED_PRECONDITION: USDT outbound balance of 100000000000 is not sufficient for order amount of 100000002641. Retrying in 5000ms.
```

**Comment by erkarl** [comment]
> Just noticed that it's not creating buy orders for me:
> 
> ```
> 2020-08-05 06:27:43.4343 [OpenDEX] trace: Creating BTC/USDT buy order with id 51d45870-dd6c-4ff1-a474-449c31c0ccf5, quantity 0.08923735 and price 11206.0704
> 2020-08-05 06:27:43.4343 [OpenDEX] trace: Creating BTC/USDT sell order with id 22bb07aa-569f-4964-8720-1bbb1fcf25ad, quantity 0.85667854 and price 12139.9096
> 2020-08-05 06:27:43.4343 [OpenDEX] trace: Order 22bb07aa-569f-4964-8720-1bbb1fcf25ad created
> 2020-08-05 06:27:43.4343 [OpenDEX] warn: 9 FAILED_PRECONDITION: USDT outbound balance of 100000000000 is not sufficient for order amount of 100000002641. Retrying in 5000ms.
> ```

Should be fixed now.

**Review by kilrau — APPROVED** [review]
Non existent pairs on OpenDEX OR CEX side should throw a nicer error message:
```
2020-08-05 10:25:52.5252 [GLOBAL] info: Starting. Hello, Arby.
2020-08-05 10:25:52.5252 [GLOBAL] info: Running with config:
LIVE_CEX: false
LOG_LEVEL: trace
DATA_DIR: /root/.arby
OPENDEX_CERT_PATH: /root/.xud/tls.cert
OPENDEX_RPC_HOST: xud
OPENDEX_RPC_PORT: 28886
MARGIN: 0.04
BASEASSET: LTC
QUOTEASSET: LTC
TEST_CENTRALIZED_EXCHANGE_BASEASSET_BALANCE: 123
TEST_CENTRALIZED_EXCHANGE_QUOTEASSET_BALANCE: 321
2020-08-05 10:25:52.5252 [Centralized] info: Base asset balance 123 and quote asset balance 321
2020-08-05 10:25:52.5252 [OpenDEX] trace: Base asset balance 5 (maxinbound: 4.899638, maxoutbound: 4.9) and quote asset balance 5 (maxinbound: 4.899638, maxoutbound: 4.9).
2020-08-05 10:25:53.5353 [Centralized] trace: LTCLTC established connection to wss://stream.binance.com:9443/ws/ltcltc@aggTrade
2020-08-05 10:25:53.5353 [Centralized] trace: heartbeat from LTCLTC socket
2020-08-05 10:26:02.022 [Centralized] warn: Price feed lost. Retrying in 5000ms.
2020-08-05 10:26:02.022 [Centralized] info: Removing CEX orders
2020-08-05 10:26:02.022 [Centralized] trace: LTCLTC stream closed
2020-08-05 10:26:02.022 [OpenDEX] warn: Failed to remove orders: Could not retrieve orders list for LTC/LTC - retrying in 1000ms
2020-08-05 10:26:03.033 [Centralized] info: Finished removing CEX orders
2020-08-05 10:26:03.033 [Centralized] info: All CEX orders have been removed
2020-08-05 10:26:03.033 [OpenDEX] warn: Failed to remove orders: Could not retrieve orders list for LTC/LTC - retrying in 1000ms
2020-08-05 10:26:04.044 [Centralized] trace: LTCLTC established connection to wss://stream.binance.com:9443/ws/ltcltc@aggTrade
2020-08-05 10:26:04.044 [Centralized] trace: heartbeat from LTCLTC socket
2020-08-05 10:26:04.044 [OpenDEX] warn: Failed to remove orders: Could not retrieve orders list for LTC/LTC - retrying in 1000ms
```

Other than that works as expected :+1:

**Comment by erkarl** [comment]
> Non existent pairs on OpenDEX OR CEX side should throw a nicer error message:
> 
> ```
> 2020-08-05 10:25:52.5252 [GLOBAL] info: Starting. Hello, Arby.
> 2020-08-05 10:25:52.5252 [GLOBAL] info: Running with config:
> LIVE_CEX: false
> LOG_LEVEL: trace
> DATA_DIR: /root/.arby
> OPENDEX_CERT_PATH: /root/.xud/tls.cert
> OPENDEX_RPC_HOST: xud
> OPENDEX_RPC_PORT: 28886
> MARGIN: 0.04
> BASEASSET: LTC
> QUOTEASSET: LTC
> TEST_CENTRALIZED_EXCHANGE_BASEASSET_BALANCE: 123
> TEST_CENTRALIZED_EXCHANGE_QUOTEASSET_BALANCE: 321
> 2020-08-05 10:25:52.5252 [Centralized] info: Base asset balance 123 and quote asset balance 321
> 2020-08-05 10:25:52.5252 [OpenDEX] trace: Base asset balance 5 (maxinbound: 4.899638, maxoutbound: 4.9) and quote asset balance 5 (maxinbound: 4.899638, maxoutbound: 4.9).
> 2020-08-05 10:25:53.5353 [Centralized] trace: LTCLTC established connection to wss://stream.binance.com:9443/ws/ltcltc@aggTrade
> 2020-08-05 10:25:53.5353 [Centralized] trace: heartbeat from LTCLTC socket
> 2020-08-05 10:26:02.022 [Centralized] warn: Price feed lost. Retrying in 5000ms.
> 2020-08-05 10:26:02.022 [Centralized] info: Removing CEX orders
> 2020-08-05 10:26:02.022 [Centralized] trace: LTCLTC stream closed
> 2020-08-05 10:26:02.022 [OpenDEX] warn: Failed to remove orders: Could not retrieve orders list for LTC/LTC - retrying in 1000ms
> 2020-08-05 10:26:03.033 [Centralized] info: Finished removing CEX orders
> 2020-08-05 10:26:03.033 [Centralized] info: All CEX orders have been removed
> 2020-08-05 10:26:03.033 [OpenDEX] warn: Failed to remove orders: Could not retrieve orders list for LTC/LTC - retrying in 1000ms
> 2020-08-05 10:26:04.044 [Centralized] trace: LTCLTC established connection to wss://stream.binance.com:9443/ws/ltcltc@aggTrade
> 2020-08-05 10:26:04.044 [Centralized] trace: heartbeat from LTCLTC socket
> 2020-08-05 10:26:04.044 [OpenDEX] warn: Failed to remove orders: Could not retrieve orders list for LTC/LTC - retrying in 1000ms
> ```
> 
> Other than that works as expected +1

Should be fixed now:
```
2020-08-06 09:27:54,564 INFO success: arby entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-06 09:27:57,568 INFO reaped unknown pid 137
Error: Invalid trading pair LTC/LTC. Supported trading pairs are: ETH/BTC, BTC/USDT
2020-08-06 09:27:57,787 INFO exited: arby (exit status 1; not expected)
```

**Review by kilrau — CHANGES_REQUESTED** [review]
I think arby should support all trading pairs that are enabled in xud. If it's not there -> error. If it's on xud, but not on CEX -> error. Wouldn't want to hard-code these.

```
Error: Invalid trading pair LTC/USDT. Supported trading pairs are: ETH/BTC, BTC/USDT
2020-08-06 09:52:30,372 INFO exited: arby (exit status 1; not expected)
2020-08-06 09:52:31,378 INFO spawned: 'arby' with pid 532
```

**Comment by erkarl** [comment]
> I think arby should support all trading pairs that are enabled in xud. If it's not there -> error. If it's on xud, but not on CEX -> error. Wouldn't want to hard-code these.
> 
> ```
> Error: Invalid trading pair LTC/USDT. Supported trading pairs are: ETH/BTC, BTC/USDT
> 2020-08-06 09:52:30,372 INFO exited: arby (exit status 1; not expected)
> 2020-08-06 09:52:31,378 INFO spawned: 'arby' with pid 532
> ```

Added `LTC/BTC` and `LTC/USDT` pairs to arby.

**Review by kilrau — APPROVED** [review]

**Pull request merged**
