### PR TITLE
feat: customize xud-docker home directory

### LINKED ISSUE #138: Do not pull updated images when update is declined
`pull.py` is pulling the latest images but that script is not only invoked when upgrading but also when starting the environment via `setup.sh`

### LINKED ISSUE #143: Customize ~/.xud-docker location
The original design was using environment variable `XUD_DOCKER_HOME` to customize the location of xud-docker directory. But it's not fully tested and I remember some part of the project hard coded `~/.xud-docker`. And it's also great to have an command line option for this customization. I suggest to use `--homedir` as the option name.

N.B. Bash getopts only support short handed option. And it's complicate to handle long handed option like `--homedir`.

### LINKED ISSUE #145: xud ctl should load, even though one of the containers is failing
I'm in an annoying situation on testnet, where the raiden container is not starting, because of
```
raiden_1     | There are no known contract addresses for network id '1'. and environment type Environment.PRODUCTION. Please provide them on the command line or in the configuration file.
```
and because of that `xud ctl` refuses to start:
```
3) Mainnet
Please choose the network: 3
Launching mainnet environment...
Failed to start service(s): raiden.
Failed to launch mainnet environment. For more details, see /home/xud/.xud-docker/mainnet/xud-docker.log
```

I would say we want:
*  `xud ctl` to start if the `xud` container is starting, ignore state of other containers
* still print warnings `Failed to start service(s): X.` for all containers refusing to start, print error dump.
* run `status` after `xud ctl` started to see container states

### PR DESCRIPTION
**Pull request by reliveyy**
Closes #145 
Closes #143 
Closes #138

This PR will provide new command line options, `--project-dir`, `--home-dir`, apart from two original options `-b|--branch`, `-d|--debug`

The **home** directory is responsible for storing all xud-docker runtime scripts that is used by all networks. The **network** (regtest, simnet, testnet, mainnet) directories are responsible for stroing the network related files like docker-compose.yml, data directory and xud-docker.log.

You could test it by running 
```
./xud.sh -b feat/customize-homedir --home-dir /path/to/home
```

### CODE REVIEW

**Comment by kilrau** [comment]
Same with `bash xud.sh -b feat/customize-homedir --home-dir ~/testi --simnet-dir ~/testi`

**Comment by kilrau** [comment]
And I tried both, allowing the updated and declining.

**Comment by kilrau** [comment]
Could you please resolve conflicts and push updated images, so that this can be tested with `-b` @reliveyy

**Comment by reliveyy** [comment]
Need to rewrite all logic in Bash so no more python dependencies will be introduced according to https://github.com/ExchangeUnion/xud-docker/issues/179

**Comment by kilrau** [comment]
> Need to rewrite all logic in Bash so no more python dependencies will be introduced according to #179

For now it's fine, please resolve conflicts and push images so that this branch can be tested as-is (with python files).

**Comment by peartobear** [comment]
Encountering this error 

````
root@ubuntu-s-2vcpu-4gb-blr1-01:~/xud-docker# ./xud.sh -b feat/customize-homedir --home-dir ~/testhomedir --simnet-dir ~/testsimnetdir
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 1
Would you like to create directory: /root/testsimnetdir? [Y/n] y
Checking files
 - banner file    ... missingChecking docker images
 - exchangeunion/lnd-simnet:latest
   SHA-256: 65070d1b1b31d46ed5396c9962861f4302116147afa585de64c4230043e7f116
   Created: 2019-09-27T09:29:33Z
   Size: 148782218 (141.88 MiB)
   * Remote image (registry-1.docker.io): exchangeunion/lnd-simnet:latest
   SHA-256: eb40c2bf34ff3e8f1815406a784c23fc15b05ac4875285f2436c0a81f2823c0a
   Created: 2019-09-19T15:19:35Z
   Status: newer
 - exchangeunion/ltcd-simnet:latest
   SHA-256: aee222d7c89cbc48152cbbe22511df5e2fe3abbc1535ad383d4f051e97b40caa
   Created: 2019-09-27T09:29:33Z
   Size: 44796686 (42.72 MiB)
   * Remote image (registry-1.docker.io): exchangeunion/ltcd-simnet:latest
   SHA-256: d65764f5f6a8d2e2278e429ba20c6cb17ae892dd7abad290f6bb04637a2c51c4
   Created: 2019-09-12T15:08:52Z
   Status: newer
 - exchangeunion/raiden-simnet:latest
   SHA-256: a37469b900d389f23ba55d07826c357721b996a64d3703286abc50fab6b6365f
   Created: 2019-09-27T09:29:33Z
   Size: 225237460 (214.80 MiB)
   * Remote image (registry-1.docker.io): exchangeunion/raiden-simnet:latest
   SHA-256: 406091acede9159f38b3b930ebc306bb2e9e137caaedcc8d3f6db4750eb77fba
   Created: 2019-09-19T15:19:35Z
   Status: newer
 - exchangeunion/xud-simnet:latest
   SHA-256: f465352f6158b8e10970a756d8a3825befc17542561117555fbb95532d8824f3
   Created: 2019-09-30T05:07:11Z
   Size: 417271805 (397.94 MiB)
   * Remote image (registry-1.docker.io): exchangeunion/xud-simnet:latest
   SHA-256: 268a1e4046a9b73a460beb76919fe676216cf058d8c1491106db5ea365c09a82
   Created: 2019-09-19T15:19:35Z
   Status: newer
A new version is available. Would you like to upgrade (Warning: this may restart your environment and cancel all open orders)? [Y/n] 
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
cat: docker-compose.yml: No such file or directory
```

**Comment by reliveyy** [comment]
@kilrau 

I'm sorry for your misuse of `--project-dir`. I should explain it more clearly in this PR's description.

`--project-dir` is used for **fully** local development. If the user specify it then xud-docker will not update from our GitHub repository. It will update from your local project directory instead. So you will not need to push commits to a remote branch anymore. So you should use `--home-dir` instead which default value is `~/.xud-docker`

Here are the responses for all your points above:

1. It's OK to remove `--<network>-dir` customization options. 
2. I learned `[Y/n]` from ArchLinux pacman, Ubuntu apt-get and CentOS yum. They use capitalized Y to indicate Yes is the default action namely when you type Enter only you will choose Yes by default. I think we should follow this convension.
3. This should be resolved by using `--home-dir` instead
4. This is caused by misusing `--project-dir` too

**Comment by reliveyy** [comment]
@peartobear I believed your case should be resolved already. Please leave a comment if you still have some problems.

**Comment by peartobear** [comment]
@reliveyy 

Built with head at `51b873d`  This specific problem is solved but simnet doesn't start as it keeps waiting for LND channels to become active , which I suspect isn't related to this specific branch changes. Full terminal output below. Also, `banner` files still prints missing but builds regardless. 

`root@ubuntu-s-2vcpu-4gb-blr1-01:~/xud-docker# ./xud.sh -b feat/customize-homedir --home-dir ~/testhomedir
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 1
Would you like to create directory: /root/testhomedir? [Y/n] y
Would you like to create directory: /root/testhomedir/simnet? [Y/n] Y
Checking files
 - banner file    ... missing   
 - init script    ... missing   
 - status script  ... missing   
 - wrapper script ... missing   
 - compose file   ... missing   
Checking docker images
 - exchangeunion/lnd-simnet:latest
   SHA-256: 65070d1b1b31d46ed5396c9962861f4302116147afa585de64c4230043e7f116
   Created: 2019-09-27T09:29:33Z
   Size: 148782218 (141.88 MiB)
   * Remote image (registry-1.docker.io): exchangeunion/lnd-simnet:latest
   SHA-256: 87c1ee6721117915fa1bd2cf4923fda065fb6d7154c6e25d529ad214fa014bee
   Created: 2019-10-01T13:04:56Z
   Status: outdated
 - exchangeunion/ltcd-simnet:latest
   SHA-256: aee222d7c89cbc48152cbbe22511df5e2fe3abbc1535ad383d4f051e97b40caa
   Created: 2019-09-27T09:29:33Z
   Size: 44796686 (42.72 MiB)
   * Remote image (registry-1.docker.io): exchangeunion/ltcd-simnet:latest
   SHA-256: 0f0a85c1a90059cbb37abeb8d91bf5985b04a0b125b047e712bb9af12d311b5f
   Created: 2019-09-30T18:02:48Z
   Status: outdated
 - exchangeunion/raiden-simnet:latest
   SHA-256: 104d6448e10e23bff9fd4b800d4caf19e245753118e2d0fad30f21bcea4fe36b
   Created: 2019-09-30T15:32:31Z
   Size: 267024726 (254.65 MiB)
   * Remote image (registry-1.docker.io): exchangeunion/raiden-simnet:latest
   SHA-256: b9cd771056821538fb0ea487b8b529e3e5eddc9d2a08d1588773cb91866fdec5
   Created: 2019-09-30T18:02:48Z
   Status: outdated
 - exchangeunion/xud-simnet:latest
   SHA-256: f465352f6158b8e10970a756d8a3825befc17542561117555fbb95532d8824f3
   Created: 2019-09-30T05:07:11Z
   Size: 417271805 (397.94 MiB)
   * Remote image (registry-1.docker.io): exchangeunion/xud-simnet:latest
   SHA-256: 6569ad5b54b20e3593c3c5dc22e11e59145b3ba7270ceef49c5b1aa1e71b9a0c
   Created: 2019-09-30T18:02:48Z
   Status: outdated
A new version is available. Would you like to upgrade (Warning: this may restart your environment and cancel all open orders)? [Y/n] y
📄 Updating file: banner.txt
📄 Updating file: init.sh
📄 Updating file: status.py
📄 Updating file: xucli_create_wrapper.py
📄 Updating file: /root/testhomedir/simnet/docker-compose.yml
📦 Updating image: exchangeunion/lnd-simnet:latest
latest: Pulling from exchangeunion/lnd-simnet
9d48c3bd43c5: Already exists 
474c611eed41: Pull complete 
bb4256c48fd2: Pull complete 
a6ec5ca085f3: Pull complete 
798d2612eace: Pull complete 
052d756ef055: Pull complete 
25873a2683b2: Pull complete 
a0b599da5c9d: Pull complete 
Digest: sha256:1cfec26e26330424d288711a133e545c64d6bda167eea068e8c95bd67732ba1d
Status: Downloaded newer image for exchangeunion/lnd-simnet:latest
docker.io/exchangeunion/lnd-simnet:latest
📦 Updating image: exchangeunion/ltcd-simnet:latest
latest: Pulling from exchangeunion/ltcd-simnet
9d48c3bd43c5: Already exists 
cea554148ac0: Pull complete 
3e9a8f1a376a: Pull complete 
ffe8a0a94a88: Pull complete 
Digest: sha256:e82c4950a343d08ca671aabbccd89a073847b90b7d0111e4087922b9df71297f
Status: Downloaded newer image for exchangeunion/ltcd-simnet:latest
docker.io/exchangeunion/ltcd-simnet:latest
📦 Updating image: exchangeunion/raiden-simnet:latest
latest: Pulling from exchangeunion/raiden-simnet
9d48c3bd43c5: Already exists 
c0ea575d71b9: Already exists 
0f535eceebd5: Already exists 
8a30f5893bea: Already exists 
c1d30ace7b67: Already exists 
e4b111bb7401: Pull complete 
e9e6af2cac41: Pull complete 
582876c34222: Pull complete 
5bb08db280de: Pull complete 
Digest: sha256:865bbfa115cfea5dcdf59b6a36c15501527ea36708ffed9589ff8f9efc088cf3
Status: Downloaded newer image for exchangeunion/raiden-simnet:latest
docker.io/exchangeunion/raiden-simnet:latest
📦 Updating image: exchangeunion/xud-simnet:latest
latest: Pulling from exchangeunion/xud-simnet
e7c96db7181b: Already exists 
50958466d97a: Already exists 
56174ae7ed1d: Already exists 
284842a36c0d: Already exists 
e366e8dd16c7: Pull complete 
93ac6b6606e9: Pull complete 
317de4965487: Pull complete 
4e50ef71ef53: Pull complete 
b3c322c7a7ca: Pull complete 
ca0fb8c506f5: Pull complete 
13380eddd554: Pull complete 
327dcfab65a5: Pull complete 
63d213eaf0d5: Pull complete 
0bd64a5888e7: Pull complete 
f3c39311c589: Pull complete 
74a155e25ba5: Pull complete 
Digest: sha256:795dec06d3e68e2080d4b524e3352bb4caec862fc8140d049957812cd9f01969
Status: Downloaded newer image for exchangeunion/xud-simnet:latest
docker.io/exchangeunion/xud-simnet:latest
🚀 Launching simnet environment
Recreating simnet_ltcd_1   ... done
Recreating simnet_raiden_1 ... done
Recreating simnet_lndbtc_1 ... done
Recreating simnet_xud_1    ... done
Recreating simnet_lndltc_1 ... done

                           .___           __  .__   
          ___  _____ __  __| _/     _____/  |_|  |  
          \  \/  /  |  \/ __ |    _/ ___\   __\  |  
           >    <|  |  / /_/ |    \  \___|  | |  |__
          /__/\_ \____/\____ |     \___  >__| |____/
                \/          \/         \/           
--------------------------------------------------------------

Waiting for LND channels to be active
.............................................................`

**Comment by sangaman** [comment]
I'm working on testing this. One minor thing for now:

>  You should NOT accept y for Y. Everything that is NOT Y should exit the script.

I've been under the impression that when prompted with `Would you like to create directory: /home/kilrau/test? [Y/n]` the capitalized letter is the default option, not that you must literally enter a capitalized letter as input. I would expect `Y`, `y`, or nothing to create the directory, `n` or `N` not to create the directory, and anything else to prompt the user again.

**Comment by kilrau** [comment]
> waiting for LND channels to become active , which I suspect isn't related to this specific branch changes

It indeed is not: https://github.com/ExchangeUnion/xud-docker/issues/171 @peartobear . @michael1011 managed to fix it with local builds, but somehow when pulling from dockerhub the images still have this problem. He's on it tho.

> I would expect Y, y, or nothing to create the directory, n or N not to create the directory, and anything else to prompt the user again.

Tested this on some other linux inputs, (e.g. `sudo apt upgrade`) and you are mostly right, here's how it should be:
* `Y`, `y`, empty approve
* entering anything else (including space) aborts and exits

**Comment by kilrau** [comment]
In future we should update https://github.com/ExchangeUnion/Docs/ when we add/remove/change parameters in a PR like this. I'll do this for this one.

**Comment by sangaman** [comment]
> Tested this on some other linux inputs, (e.g. `sudo apt upgrade`) and you are mostly right, here's how it should be and TODO:
> 
>     * `Y`, `y`, empty/nothing approve
> 
>     * entering anything else (including space) aborts and exits

We might want to apply this to some other prompts too, for instance `A new version is available. Would you like to upgrade (Warning: this will restart your environment and cancel all open orders)?` doesn't upgrade if you just press enter. I can open a separate issue.

**Comment by erkarl** [comment]
I'm experiencing the following output when answering "no" to upgrade using a clean environment:
```
A new version is available. Would you like to upgrade (Warning: this may restart your environment and cancel all open orders)? [Y/n] n
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

grep: docker-compose.yml: No such file or directory
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

**Comment by reliveyy** [comment]
@erkarl I should handle the case when all files are missing and should not give the user upgrade choice because xud-docker is not installed in this case.

**Comment by erkarl** [comment]
@reliveyy thanks for fixing that. Looks good. 1 more thing - I noticed that automatic `xucli create` is not functioning in this branch when creating a fresh environment.

**Comment by kilrau** [comment]
Also, could you update the PR description (there are unimplemented cli parameters now)?

**Comment by reliveyy** [comment]
> Automatic xucli create is not functioning in this branch when creating a fresh environment.
@erkarl I cannot reproduce your case in testnet and mainnet. Could you please retry it because I rebased this branch after your comment.

**Comment by kilrau** [comment]
docs.exchangeunion.com should be updated at the same time. Shall I do that? @reliveyy

**Pull request merged**
