### PR TITLE
fix: add neutrino assumechanvalid option to fix sync

### PR DESCRIPTION
**Pull request by kilrau**
- adding `routing.assumechanvalid` for lndbtc/lndltc on all networks along with all build tags with lnd (needs experimental)
- straighten `alpine` images to `3.11` and `go` to `1.14`, so that we don't have to update for point releases
- rename lnd `-patched` -> `-simnet`
- upgrade to lndbtc 0.10 for testnet & mainnet

How to test:
`bash xud.sh -b fix/neutrino-assumchanvalid`

Simnet Dependency: https://github.com/ExchangeUnion/xud-docker/pull/464 by @erkarl 
Testnet Dependency: connext indra rinkeby node by @erkarl

### CODE REVIEW

**Comment by kilrau** [comment]
Did you test if the lnd assumechanvalid option was succesfully applied on testnet & mainnet too (because I did not)? @raladev

**Comment by raladev** [comment]
Testnet in neutrino mod:
- [ ] There is no btclnd image with this branch for testnet. exchangeunion/lnd:0.9.2-beta is used instead of that.
[Screenshot from 2020-05-20 16-15-08](https://user-images.githubusercontent.com/29906866/82450227-19278580-9ab5-11ea-884a-e3b63061f2bb.png)
- [ ] lndltc is crashed with neutrino mode.
[Screenshot from 2020-05-20 16-16-26](https://user-images.githubusercontent.com/29906866/82450377-4d02ab00-9ab5-11ea-8e59-afbf90138904.png)

**Comment by kilrau** [comment]
Oh dang, thanks @michael1011 . I fixed the config and LND's sync fine in neutrino mode now (verified via docker logs). Both synced in ~5 minutes. I guess you didn't go throw the `Create New` environment flow though?

Because now we are hitting the same annoying problem as on simnet (xud being disconnected from LND's and lnd's missing admin.macaroons). Can you add the exact same `Client restart necessary.` logic as on simnet to this PR (and test that it actually works)? @reliveyy

**Comment by reliveyy** [comment]
@kilrau you mean restarting logic for **testnet**?

**Comment by kilrau** [comment]
Did 2 more testruns on testnet and 2 more on mainnet and all 4 worked fine. So looks like this was a weird edge case I hit there and we can leave as is.

Ready to merge.

**Pull request merged**
