### PR TITLE
chore: cleanup

### PR DESCRIPTION
**Pull request by reliveyy**
Closes https://github.com/ExchangeUnion/xud-docker/issues/255

This PR removed unused files in this project.
* Removed `tests` folder and `test/qemu` will replace original test code
* Removed xud-network folder becuase we do not need docker-compose anymore
* Removed `init.sh`, `status.sh` and `status2.sh` becuase their functionality is included in utils container
* Removed `.travis.yml` and we will add travis or github actions CI support in the future.

### CODE REVIEW

**Comment by kilrau** [comment]
That's huge. Could you give a little description (every PR should have that) and link it to an issue (e.g. https://github.com/ExchangeUnion/xud-docker/issues/255)? @reliveyy

**Comment by kilrau** [comment]
Also this is not testable since the utils container is not pushed:
```
~$ xud -b chore/cleanup
Failed to pull exchangeunion/utils:latest__chore-cleanup
```

**Comment by erkarl** [comment]
@reliveyy should this be testable via `bash xud.sh -b chore/cleanup`?

**Comment by reliveyy** [comment]
> @reliveyy should this be testable via `bash xud.sh -b chore/cleanup`?

Yes

**Comment by reliveyy** [comment]
> That's huge. Could you give a little description (every PR should have that) and link it to an issue (e.g. #255)? @reliveyy

Updated

**Pull request merged**
