### PR TITLE
feat(tor): use native xud-tor integration

### PR DESCRIPTION
**Pull request by ghost**
This PR removes proxychains dependency in our xud images in favour of native tor integration.

Steps to test:
`bash xud.sh -b native-tor-support`

Verify that you're able to connect to onion addresses. For example on testnet:
`xucli connect 
037a74737630bb5a9979762b2163ef9f95c81e00caf347bacc17f16991cdbb61f7@pso32ae2l5nyh3clgee2nj2hgpmcnluhaqibjm2r2fjcsn4gclxfmrid.onion`

### CODE REVIEW

**Review by peartobear — APPROVED** [review]
works like charm

**Review by kilrau — CHANGES_REQUESTED** [review]
The advertised URI appears as:
```
├───────────────────────────────────────────────────────────────────────┼──────────┼─────────────────────────────────────────┤
│ Alias:                                                                │ WETH/BTC │ inbound: true                           │
│                                                                       │ BTC/DAI  │ version: 1.0.0-beta                     │
│ Address ([node_key]@[host]:[port]):                                   │ LTC/BTC  │ time connected: 49 seconds              │
│ 0334811d66d0f52492dfafe72c2da0e735d293c545eeeadcc0cddf636ae13888d9    │ LTC/DAI  │ BTC lnd key: 02f56e13b8...c7eb41ec97    │
│ @127.0.0.1:47520                                                      │          │ LTC lnd key: 02f56e13b8...c7eb41ec97    │
│                                                                       │          │ raiden address: 0xB0Fc38BB...5bd92FD9d0 │
└───────────────────────────────────────────────────────────────────────┴──────────┴─────────────────────────────────────────┘
```

It should show the onion address and port 18885. We should fix that, otherwise connecting back won't work.

**Review by reliveyy — APPROVED** [review]

**Comment by erkarl** [comment]
> The advertised URI appears as:
> 
> ```
> ├───────────────────────────────────────────────────────────────────────┼──────────┼─────────────────────────────────────────┤
> │ Alias:                                                                │ WETH/BTC │ inbound: true                           │
> │                                                                       │ BTC/DAI  │ version: 1.0.0-beta                     │
> │ Address ([node_key]@[host]:[port]):                                   │ LTC/BTC  │ time connected: 49 seconds              │
> │ 0334811d66d0f52492dfafe72c2da0e735d293c545eeeadcc0cddf636ae13888d9    │ LTC/DAI  │ BTC lnd key: 02f56e13b8...c7eb41ec97    │
> │ @127.0.0.1:47520                                                      │          │ LTC lnd key: 02f56e13b8...c7eb41ec97    │
> │                                                                       │          │ raiden address: 0xB0Fc38BB...5bd92FD9d0 │
> └───────────────────────────────────────────────────────────────────────┴──────────┴─────────────────────────────────────────┘
> ```
> 
> It should show the onion address and port 18885. We should fix that, otherwise connecting back won't work.

Is that the output from `listpeers`? If so, that's expected for inbound peers.

`getinfo` call should show the true advertised address of the node.

**Comment by kilrau** [comment]
> Is that the output from `listpeers`? If so, that's expected for inbound peers.

Yes

> `getinfo` call should show the true advertised address of the node.

Then we should change the behavior of `listpeers` to show the advertised listening URI. If none, just show pubkey. WDYT? @sangaman @erkarl

**Comment by kilrau** [comment]
Stuck after creating images (I `docker system prune -a`d before):
```
kilrau@K-Yoga:~$ xud -b native-tor-support
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 2
🚀 Launching testnet environment
🌍 Checking for updates ...
Failed to check for image updates. Try again? [Y/n] y
* Image exchangeunion/raiden:latest: missing
* Image exchangeunion/lnd:0.8.2-beta: missing
* Image exchangeunion/xud:latest: missing
* Image exchangeunion/litecoind:0.17.1: missing
* Image exchangeunion/bitcoind:0.19.0.1: missing
* Image exchangeunion/geth:1.9.10: missing
* Container testnet_bitcoind_1: missing
* Container testnet_litecoind_1: missing
* Container testnet_lndbtc_1: missing
* Container testnet_lndltc_1: missing
* Container testnet_raiden_1: missing
* Container testnet_xud_1: missing
Pulling exchangeunion/raiden:latest
Pulling exchangeunion/lnd:0.8.2-beta
Pulling exchangeunion/xud:latest
Pulling exchangeunion/litecoind:0.17.1
Pulling exchangeunion/bitcoind:0.19.0.1
Pulling exchangeunion/geth:1.9.10
Creating testnet_bitcoind_1
Creating testnet_litecoind_1
Creating testnet_lndbtc_1
Creating testnet_lndltc_1
Creating testnet_raiden_1
Creating testnet_xud_1
^C
^C
kilrau@K-Yoga:~$ xud -b native-tor-support
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 2
🚀 Launching testnet environment
🌍 Checking for updates ...
All up-to-date.
```
[testnet.log](https://github.com/ExchangeUnion/xud-docker/files/4245550/testnet.log)

**Comment by sangaman** [comment]
> Stuck after creating images (I `docker system prune -a`d before):

I'm getting the same, tried stopping and removing all images and this is still the case.

```
$ bash xud.sh -b native-tor-support
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 2
🚀 Launching testnet environment
🌍 Checking for updates ...
* Container testnet_bitcoind_1: missing
* Container testnet_litecoind_1: missing
* Container testnet_geth_1: missing
* Container testnet_lndbtc_1: missing
* Container testnet_lndltc_1: missing
* Container testnet_raiden_1: missing
* Container testnet_xud_1: missing
Creating testnet_bitcoind_1
Creating testnet_litecoind_1
Creating testnet_geth_1
Creating testnet_lndbtc_1
Creating testnet_lndltc_1
Creating testnet_raiden_1
Creating testnet_xud_1
```

**Comment by erkarl** [comment]
@sangaman could you please also attach your testnet.log so that I can compare it with @kilrau 's. I'm unable to reproduce the issue with a clean start: `sudo rm -Rf ~/.xud-docker && docker system prune -a`.

**Comment by kilrau** [comment]
Tried again with my existing testnet environment, now stuck here:
```
kilrau@K-Yoga:~$ xud -b native-tor-support
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 2
🚀 Launching testnet environment
🌍 Checking for updates ...
* Container testnet_xud_1: outdated
A new version is available. Would you like to upgrade (Warning: this may restart your environment and cancel all open orders)? [Y/n] Y
Recreating testnet_xud_1
```

**Review by kilrau — APPROVED** [review]

**Comment by erkarl** [comment]
> > Is that the output from `listpeers`? If so, that's expected for inbound peers.
> 
> Yes
> 
> > `getinfo` call should show the true advertised address of the node.
> 
> Then we should change the behavior of `listpeers` to show the advertised listening URI. If none, just show pubkey. WDYT? @sangaman @erkarl

Created https://github.com/ExchangeUnion/xud/issues/1410 as a follow-up.

**Comment by erkarl** [comment]
@sangaman the issue was related to the existing data directory using a higher version of lnd (and the database migration failing).

After pushing the new image we tested with @kilrau that it's no longer an issue.

**Pull request merged**
