### PR TITLE
chore: upgrade alpine to 3.12

### PR DESCRIPTION
**Pull request by reliveyy**

### CODE REVIEW

**Comment by raladev** [comment]
I removed approval until travis builds are not passed.

**Comment by kilrau** [comment]
True. Restarted these.

**Comment by kilrau** [comment]
Your last commit bumps go 1.13 -> 1.14 which caused issues with lnd 0.9.X, but should be ok with lnd 0.10.X. So let's carefully test this in the wild before merging.

**Comment by reliveyy** [comment]
The node:12-alpine3.12 and node:14-alpine3.12 only have linux/amd64 image. We are blocking due to this.

**Comment by reliveyy** [comment]
Close this long pending issue.

**Comment by kilrau** [comment]
Why?

**Comment by kilrau** [comment]
Just needs testing, thats all.

**Comment by reliveyy** [comment]
> Why?

Becuase this PR is based on old `images/<name>/<tag>` folder structure. I will create a new PR based on `images/<name>` structure later. @kilrau

**Pull request closed without merging**
