### PR TITLE
feat(arby): upgrade mainnet to v1.1.8

### PR DESCRIPTION
**Pull request by ghost**
This PR upgrades arby to v1.1.6 which should mitigate the issue with orders updating too quickly for the decentralized orderbook. Orders are now updated only if a greater than 0.1% price movement happens. 

**Please test `arby:latest` on simnet/testnet before merging this.**

### CODE REVIEW

**Comment by raladev** [comment]
- [ ] no order recreation after price feed lost err - after the error i still need to wait required price change to get new orders, but old orders were removed because of price feed err. 
[Screenshot from 2020-08-25 21-57-04](https://user-images.githubusercontent.com/29906866/91216191-3906bf00-e71e-11ea-94ab-ead305d48804.png)

**Review by raladev — DISMISSED** [review]
above

**Comment by kilrau** [comment]
> Solutions:
>     1. add order recreation after successful trade;
>     2. add time throttling in addition to price throttling (preferable, because it will make orderbook more active).

I believe #1 is the correct thing to do. There is no need for the orderbook to "look active" as in "constantly changing prices". The liquidity just needs to be there and more importantly swaps need to work reliably.

**Comment by kilrau** [comment]
What's your take? @erkarl

**Comment by raladev** [comment]
not sure but with several orders in row it may lead to several noOrderErr's.

**Comment by erkarl** [comment]
@raladev ready for testing again.

**Comment by raladev** [comment]
- [ ] order replacing after swap works for buy orders buy not for sell orders
[Screenshot from 2020-08-27 21-05-18](https://user-images.githubusercontent.com/29906866/91481993-fd026400-e8ad-11ea-9db4-ce32c73f25df.png)
[Screenshot from 2020-08-27 21-03-19](https://user-images.githubusercontent.com/29906866/91482001-fecc2780-e8ad-11ea-9d44-9821f2aa6245.png)

- [ ] there is a problem with network blinking. If i get small network issue and my channel became inactive, my Base and Quote assets will be aqual 0 when Create order action will be reached after price feed recovery, as a result i will not get orders and will need to wait channel activation (~2-5 mins for me on simnet) and price changing (i waited 15 mins).

[Screenshot from 2020-08-27 21-16-09](https://user-images.githubusercontent.com/29906866/91482203-5a96b080-e8ae-11ea-8e41-75f070e39849.png)

- [ ] Unrecoverable error may be reached during continuous matching. i get 9 successful swaps of 15 (6 of them were not matched because orderbook was empty because of unrecoverable error). Root case is get part of order in hold when replace order. I reached 5 errors for 9 swaps (see arby log). tool_output is a just output of placeOrders calls from taker.

[tool_output.log](https://github.com/ExchangeUnion/xud-docker/files/5138224/tool_output.log)
[arby_unrec.log](https://github.com/ExchangeUnion/xud-docker/files/5138225/arby_unrec.log)

- should we replace order before or after CEX order filling? @kilrau @erkarl

**Review by raladev — CHANGES_REQUESTED** [review]
Above

**Comment by erkarl** [comment]
>     * [ ]  order replacing after swap works for buy orders but not for sell orders
>       [Screenshot from 2020-08-27 21-05-18](https://user-images.githubusercontent.com/29906866/91481993-fd026400-e8ad-11ea-9db4-ce32c73f25df.png)
>       [Screenshot from 2020-08-27 21-03-19](https://user-images.githubusercontent.com/29906866/91482001-fecc2780-e8ad-11ea-9d44-9821f2aa6245.png)
> 
>     * [ ]  there is a problem with network blinking. If i get small network issue and my channel became inactive, my Base and Quote assets will be aqual 0 when Create order action will be reached after price feed recovery, as a result i will not get orders and will need to wait channel activation (~2-5 mins for me on simnet) and price changing (i waited 15 mins).
> 
> 
> [Screenshot from 2020-08-27 21-16-09](https://user-images.githubusercontent.com/29906866/91482203-5a96b080-e8ae-11ea-8e41-75f070e39849.png)
> 
>     * [ ]  Unrecoverable error may be reached during continuous matching. i get 9 successful swaps of 15 (6 of them were not matched because orderbook was empty because of unrecoverable error). Root case is get part of order in hold when replace order. I reached 5 arby errors for 9 swaps (see arby log). tool_output is a just output of placeOrders calls from taker.
> 
> 
> [tool_output.log](https://github.com/ExchangeUnion/xud-docker/files/5138224/tool_output.log)
> [arby_unrec.log](https://github.com/ExchangeUnion/xud-docker/files/5138225/arby_unrec.log)
> 

The first 2 issue should now be addressed.

Created a follow-up issue for the 3rd one: https://github.com/ExchangeUnion/market-maker-tools/issues/84

> * should we replace order before or after CEX order filling? @kilrau @erkarl

Doesn't matter. It happens in parallel.

**Review by raladev — APPROVED** [review]

**Pull request merged**
