### PR TITLE
apply create/restore flow for simnet

### PR DESCRIPTION
**Pull request by kilrau**
This prevents the 2h syncs on simnet which some of us experienced. Normal sync time until channels are active should be 15 minutes.

### CODE REVIEW

**Comment by kilrau** [comment]
- [ ] Neutrino % shows 100 immediately after up:

```
├─────────┼──────────────────────────────────────────────────┤
│ lndbtc  │ Ready 100.00% (29633/29633)                      │
├─────────┼──────────────────────────────────────────────────┤
│ lndltc  │ Ready 100.00% (29711/29711)                      │
├─────────┼──────────────────────────────────────────────────┤

```

- [ ] remove 15s sleep

**Comment by raladev** [comment]
1. fix with tls.cert waiting works for me (I got 'I xud is starting... try again in a few seconds' or 'timed out waiting for cert to be created at /root/.xud/tls.cert');
2. empty fields in getinfo for LTC and BTC nodes + errors in xud logs when use getinfo.
To fill them, one more restart of xud is required; After restart I got data in getinfo and opened channels;
[Screenshot](https://user-images.githubusercontent.com/29906866/80618984-c24a0580-8a4c-11ea-9798-d03d6d94c5c9.png)
[unlock.log](https://github.com/ExchangeUnion/xud-docker/files/4552880/unlock.log)
3. It seems we should not give access to xucli before+during restart attempt. Restart is a part of installation process and if we give access to xucli before restart it looks like a little bit strange: waiting - could not connect - empty cell - starting(see file - 
[restart_status.log](https://github.com/ExchangeUnion/xud-docker/files/4552919/restart_status.log)
) 
4.If you dont want retry after failed checking of backup location and press N, 'Stopping lndbtc/lndlts/...' tooks ~ 3-5 mins; (It seems they cant gracefully shutdown);
[backup_stop.log](https://github.com/ExchangeUnion/xud-docker/files/4552968/backup_stop.log)
5. I did not see Sync status for lnd. Most of time it was Container Running and after some time it become Ready, but maybe i missed something.

**Comment by kilrau** [comment]
Thanks for the detailed test @raladev ! I gave the same feedback: don't enter `xud ctl` before all restarts are complete and xud returns locked. I believe most of your issues will be addressed in @reliveyy 's last commit, I will test on my end once the build is through and let you know.

**Comment by raladev** [comment]
4.If you dont want retry after failed checking of backup location and press N, 'Stopping lndbtc/lndlts/...' tooks ~ 3-5 mins; (It seems they cant gracefully shutdown); **fixed partially**

**Comment by raladev** [comment]
auto-unlock works correctly.
Cases:
ask pwd after installation+restart;
ask pwd after xud container restart + xud.sh;
dont ask when xud.sh with unlocked xud;
Ctrl+C to skip auto-asking;
Ctrl+C to skip asking after unlock command.

**Pull request merged**
