### PR TITLE
feat: switch back to geth

### PR DESCRIPTION
**Pull request by michael1011**
Closes https://github.com/ExchangeUnion/xud-docker/issues/96 and https://github.com/ExchangeUnion/xud-docker/issues/94

@reliveyy for some reason Raiden fails with:
```
raiden_1     | cat: /root/.ethereum/account-testnet.txt: No such file or directory
```
Although that file clearly exists. Maybe I messed up the volumes in `xud-testnet/docker-compose.yml`? Could you please have a look at that?

### CODE REVIEW

**Comment by kilrau** [comment]
Could you give this a rebase and another test @michael1011 now that #107 is in?

**Comment by reliveyy** [comment]
> Could you give this a rebase and another test @michael1011 now that #107 is in?

I did the rebase for testing with `feat/add-geth-again` branch. But the testing on my local envionment shows raiden sitll waiting for geth(1.9.1) to synced after geth is ready. @michael1011

**Comment by michael1011** [comment]
I just fixed the account issue mentioned in my first comment with the help of @reliveyy and will rebase and sync the testnet now to reproduce your issue

**Comment by reliveyy** [comment]
One suggestion: leaving parity image folder there in case we need it in the future.

**Comment by michael1011** [comment]
@reliveyy if we need it in the future we can have a look at the repository before this PR was merged. With Git I don't see a point in keeping unused files in the repo.

**Comment by kilrau** [comment]
Conflicts..

**Comment by michael1011** [comment]
...resolved. Was just a single line.

**Comment by michael1011** [comment]
@reliveyy @kilrau @dopetard now that the TOR branch and with it supervisord is merged please have another look at this branch and give it a try.

**Comment by erkarl** [comment]
@michael1011 this is pending on us rebasing the Raiden against the latest develop, right?

**Comment by michael1011** [comment]
@erkarl right now this branch is using the latest Raiden release because that is the only one that officially supports Geth version 1.9.1. This means that the Raiden swaps don't work but I wouldn't see this as blocker for this PR because before it the Raiden image contained an older official Raiden release and not the code from our fork.

**Comment by kilrau** [comment]
Agree. Plus I would want to start re-syncing our cloud testnet instance. Once we have a raiden version rebased on develop and our changes in, we can simply replace the raiden image.

Let's merge!

**Pull request merged**
