### PR TITLE
feat(arby): add Kraken support

### PR DESCRIPTION
**Pull request by erkarl**
This adds new configuration variable `cex` to xud-docker config. Valid values are:
```
cex = "Binance"
```
or 
```
cex = "Kraken"
```

This PR also renames previous configuration variables:
`binance-api-key` -> `cex-api-key`
`binance-api-secret` -> `cex-api-secret`

### CODE REVIEW

**Review by kilrau — CHANGES_REQUESTED** [review]
- [ ] Should work with this config on simnet:
```
[arby]
base-asset = "BTC"
quote-asset = "USDT"
cex = "binance"
test-centralized-baseasset-balance = "10"
test-centralized-quoteasset-balance = "100000"
margin = "0.03"
disabled = false
```


but doesn't:
```
Error: Incomplete configuration. Please add the following options to .env or as environment variables: CEX, CEX_API_KEY, CEX_API_SECRET
2020-09-18 13:59:14,512 INFO exited: arby (exit status 1; not expected)
```

**Review by raladev — CHANGES_REQUESTED** [review]
- [ ] it seems order placing does not work because of invalid parameter in the request
`2020-09-18 02:27:35.3535 [Centralized] warn: Failed to execute CEX order: InvalidOrder: kraken {"error":["EGeneral:Invalid arguments:volume"]}. Retrying in 1000ms
`

**Review by reliveyy — DISMISSED** [review]
LGTM on code level.

**Comment by kilrau** [comment]
How it should work imo: if one of the two are set, all `cex-api` options are ignored
```
test-centralized-baseasset-balance = "10"
test-centralized-quoteasset-balance = "100000"
```
I am ok with making `cex` mandatory since it will determine where the price stream comes from.

**Comment by raladev** [comment]
> cex = "binance"
B in Binance and K in Kraken should be capitalized

**Review by kilrau — DISMISSED** [review]
> > cex = "binance"
> 
> B in Binance and K in Kraken should be capitalized

come on guys... config strings always need to work for cap and non-cap strings

**Review by raladev — APPROVED** [review]

**Review by raladev — APPROVED** [review]

**Pull request merged**
