### PR TITLE
feat(arby): add test-mode configuration option

### PR DESCRIPTION
**Pull request by ghost**
This commit deprecates the old `live-cex` configuration value in favour
of new `test-mode` option. If both values are set, the `test-mode`
option takes precedence over the legacy option.

### CODE REVIEW

**Comment by raladev** [comment]
- [ ] if i understood correctly , for now xud-docker help output is hardcoded in setup.sh, so it should be changed too

**Review by raladev — CHANGES_REQUESTED** [review]
above

**Comment by erkarl** [comment]
>     * [ ]  if i understood correctly , for now xud-docker help output is hardcoded in setup.sh, so it should be changed too

Yep, you're right.

>     * [ ]  `test-mode` should be `false` as default, that means `live-cex` is `true` as defalt

You mean `test-mode=true` should be the default, right? This is equivalent to `live-cex=false` default that we had before?

Want to take a stab at implementing these changes?

**Comment by erkarl** [comment]
@raladev changes implemented as per yesterday's discussion. `test-mode=false` is now the default for mainnet, `test-mode=true` for other networks. I also had to implement some changes from Arby's side https://github.com/ExchangeUnion/market-maker-tools/pull/115

**Comment by raladev** [comment]
- [ ] live-cex option do nothing for now 
Screenshot from 2020-10-28 16-20-36
Screenshot from 2020-10-28 16-18-47

- [ ] hardcoded help still should be changed

**Review by raladev — CHANGES_REQUESTED** [review]
above

**Comment by erkarl** [comment]
Updated @raladev

**Comment by raladev** [comment]
- [ ] syntax err 
roma@roma-ThinkPad-X1-Carbon-6th:~/.xud-docker$ bash xuid.sh -b feat/arby-config-option-change --arby.disabled false --arby.base-asset BTC --arby.quote-asset USDT --arby.margin 0.01 --arby.live-cex false
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 1
Pulling image exchangeunion/utils:latest__feat-arby-config-option-change
🚀 Launching simnet environment
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/__init__.py", line 8, in <module>
    from launcher.node import NodeManager, NodeNotFound
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/node/__init__.py", line 13, in <module>
    from .arby import Arby
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/node/arby.py", line 31
    test_mode = self.node_config["test-mode"] \
            if "test-mode" in self.node_config
                                          ^
SyntaxError: invalid syntax

**Comment by erkarl** [comment]
Sorry for that, should be fixed now.

**Review by raladev — APPROVED** [review]

**Pull request merged**
