### PR TITLE
feat: update GETH and LND images

### LINKED ISSUE #297: Update to lnd 0.9.0, geth 1.9.11
- lnd 0.9.0 simulation tests passed (https://github.com/ExchangeUnion/xud/pull/1393)
- geth 1.9.10 manual testing passed, will do the same with 1.9.11

### PR DESCRIPTION
**Pull request by michael1011**
Closes #297 

@reliveyy could you build images for this PR too after it is merged?

### CODE REVIEW

**Comment by peartobear** [comment]
I could reproduce @fagunbhavsar's issue this but it works on the second try. It takes some time to boot up so give it a wee second before trying.  
```
testnet > xucli unlock
Enter master xud password: 
xud was unlocked succesfully
The following wallets were unlocked: BTC, LTC
testnet > getinfo
could not connect to xud at localhost:8886, is xud running?
testnet > getinfo

General XUD Info
```

**Comment by kilrau** [comment]
Well I'm afraid there is only so much we can do:
- since https://github.com/ExchangeUnion/xud/pull/1302 the first thing xud does is starting the rpc server and notifying "I am starting" when called
- lnd throws similar weird errors if it's not ready

The only things we could do in docker is some artifical "Starting..." blocking screen that just makes the user wait for some seconds. Wdyt? @peartobear @fagunbhavsar

**Comment by sangaman** [comment]
Thanks everyone. There are a couple of issues here, but I don't think directly related to the changes in this PR.

1) I believe the reason we get the "is xud running" message immediately after unlocking xud is because lnd is taking a while to become responsive to any rpc calls. The call times out, xud encounters the time out error, returns it to xucli, and xucli mistakenly interprets that as *xud* timing out when it is actually lnd that has timed out. I'll open a new issue for this, we can certainly handle this situation better and print a more informative message. And ideally we shouldn't timeout our xud getinfo call just because the lnd getinfo calls time out.

2) As discussed in #195, lnd won't unlock if bitcoind/litecoind are still validating blocks. This takes some time, especially with litecoind it seems. Lnd *should* unlock automatically with the fix from https://github.com/ExchangeUnion/xud/pull/1394, but my environment is using commit `bf0b667` from 1/16 which is before that fix went in.

3) `The following wallets were unlocked: BTC, LTC` - this message is clearly wrong. I believe it's also fixed with the changes since January, but I might have to do some more investigation.

I think the reality is that lnd/bitcoind/litecoind all take some time to get to a "ready" state and that spinning up everything all at once as we do with xud-docker requires some patience. I'm not exactly sure on the best/nicest way to let users know that, perhaps a waiting screen or just clearer messages that the environment is still starting up when calls fail immediately after unlock.

> or better have the unlock call wait for a successful getinfo call, not only "unlocking". We discussed this for LND, I think we should do the same for xud. Wdyt? @sangaman

Yes probably something like this is worth doing. I think fixing 1) above would help. I'd be hesitant to make the unlock call wait though, because in reality it can take minutes for lnd/bitcoind to become fully responsive and that's a long time to wait on a call especially at the command line. Something like a response that says xud is unlocked, but we're still waiting on lnd/raiden.

**Comment by michael1011** [comment]
I just pushed a [commit to our raiden fork](https://github.com/ExchangeUnion/raiden/commit/0406f4f805c189a9f7b49285ff06a3c604fc9b65) that bumps the supported GETH version

**Pull request merged**
