### PR TITLE
feat: restore

### PR DESCRIPTION
**Pull request by reliveyy**
Closes https://github.com/ExchangeUnion/xud-docker/issues/245

This PR try to move create/restore choosing logic inside utils container.

Testing instructions:
* `bash xud.sh -b feat/restore`
* test features as described in https://github.com/ExchangeUnion/xud-docker/issues/245

### CODE REVIEW

**Comment by kilrau** [comment]
- [ ] `xud_backup = "/your/backup/path"` is persisted in `xud-docker.conf` whereas it should be in <network>.conf. Also the naming should be as in https://github.com/ExchangeUnion/xud-docker/issues/245
- [ ] starting `xud -b feat/restore` in an existing environment first worked:
```
Creating testnet_litecoind_1
Creating testnet_geth_1
Creating testnet_lndbtc_1
Creating testnet_lndltc_1
Creating testnet_raiden_1
Creating testnet_xud_1
Backup location not available.
Enter path to backup location:
``` which I aborted with CTRL+C. Now env fails to start with:
```
kilrau@K-Yoga:~/.xud-docker$ xud -b feat/restore
mktemp: too few X's in template ‘xud-docker’
```

**Comment by kilrau** [comment]
Can't launch existing testnet environment because it can't write logs (permissions didn't change, see ls -la output):
```
kilrau@K-Yoga:~/.xud-docker/testnet$ ls -la
total 924
drwxr-xr-x 3 kilrau kilrau   4096 Feb 16 20:15 .
drwxr-xr-x 4 kilrau kilrau   4096 Feb 17 13:50 ..
drwxr-xr-x 9 root   root     4096 Jan 31 12:05 data
-rw-r--r-- 1 root   root     1483 Feb 15 00:16 history
-rw-r--r-- 1 root   root     4542 Feb  6 18:48 init.sh
-rw-r--r-- 1 root   root     1435 Feb 15 11:55 sample-testnet.conf
-rw-r--r-- 1 root   root     1515 Feb 15 11:54 testnet.conf
-rw-r--r-- 1 root   root   907701 Feb 16 18:38 testnet.log
kilrau@K-Yoga:~/.xud-docker/testnet$ xud -b feat/restore
Unable to find image 'exchangeunion/utils:latest__feat-restore' locally
latest__feat-restore: Pulling from exchangeunion/utils
4167d3e14976: Pull complete 
1baf8a687be7: Pull complete 
222352708f88: Pull complete 
b4c0cab59d3d: Pull complete 
59d143c1dde1: Pull complete 
f05b1663d591: Pull complete 
0de5cc6e2730: Pull complete 
1f9d55c122d4: Pull complete 
b3db6dbc6a49: Pull complete 
0df429e92533: Pull complete 
fb731c593624: Pull complete 
f4e16b10a378: Pull complete 
574f885dd151: Pull complete 
Digest: sha256:6bfc2ddde30b8b14fe7ed8feafa7e5c63e8843daf2c87d18f81f160679d09388
Status: Downloaded newer image for exchangeunion/utils:latest__feat-restore
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 2
🚀 Launching testnet environment
/dev/fd/63: line 328: /home/kilrau/.xud-docker/testnet/testnet.log: Permission denied
```

**Comment by kilrau** [comment]
- [ ] NO BACKUP IS WRITTEN TO THE SPECIFIED FOLDER and I am pretty sure because xud is still on `1.0.0-mainnet-b2e4c87-dirty` (I'm using amd64 testnet)

**Comment by reliveyy** [comment]
@kilrau 

> never update the user's config file ...

Done. Moved xud-docker option from sample-xud-docker.conf to sample-&lt;network&gt;.conf

> Still part of sample-xud-docker.conf ...

Done.

> Can't launch existing testnet environment because it can't write logs

Done.

> ... we can just append (linux timestamp) e.g. testnet-1581944907.log ...

Done.

> ... it adds the entry to the confi file instead of overwritiing it ...

To be tested.

> NO BACKUP IS WRITTEN TO THE SPECIFIED FOLDER

To be tested.

> Backup location not available comes up even though it is available, maybe give the check 1s sleep

Not pretty sure about your case. I create the backup directory then enter the path after the prompt. It always pass the check.

> Never assume any default location for backup.

Done.

> ... copy paste ...

Won't fix in this PR.

**Comment by kilrau** [comment]
- [ ] throws this when backup dir (in testnet.conf) is not available on start, should ask `Backup location not available. Enter path to backup location:` as above.
```
$ xud -b feat/restore
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 2
🚀 Launching testnet environment
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/launcher/__main__.py", line 3, in <module>
    Launcher().launch()
  File "/usr/local/lib/python3.8/site-packages/launcher/launcher.py", line 765, in __init__
    self._config = Config()
  File "/usr/local/lib/python3.8/site-packages/launcher/config/config.py", line 144, in __init__
    self.backup_dir = os.environ["BACKUP_DIR"]
  File "/usr/local/lib/python3.8/os.py", line 673, in __getitem__
    raise KeyError(key) from None
KeyError: 'BACKUP_DIR'
```
When I made the backup-dir availalble, it threw the same.

**Comment by kilrau** [comment]
- [ ] Entering a wrong path should down all containers (regular `down` script) + `not existed` -> `Checking backup location... Failed. Retry? [y/N] N` as described in https://github.com/ExchangeUnion/xud-docker/issues/245.
```
Enter path to backup location: asdflj
Checking... Failed (not existed). Retry? [y/N] n
kilrau@K-Yoga:~/.xud-docker/testnet$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
d5d0f0390825        exchangeunion/xud:latest          "/usr/bin/supervisor…"   55 seconds ago      Up 53 seconds       8885/tcp, 8887/tcp, 0.0.0.0:18885->18885/tcp           testnet_xud_1
4ff8f1a07711        exchangeunion/raiden:latest       "/usr/bin/supervisor…"   55 seconds ago      Up 53 seconds       5001/tcp                                               testnet_raiden_1
3b9930c290f5        exchangeunion/lnd:0.8.2-beta      "/usr/bin/supervisor…"   55 seconds ago      Up 53 seconds       9735/tcp, 10009/tcp, 10735/tcp, 19735/tcp, 20735/tcp   testnet_lndltc_1
0c3332f7d8c8        exchangeunion/lnd:0.8.2-beta      "/usr/bin/supervisor…"   55 seconds ago      Up 53 seconds       9735/tcp, 10009/tcp, 10735/tcp, 19735/tcp, 20735/tcp   testnet_lndbtc_1
c011ff3b27e4        exchangeunion/litecoind:0.17.1    "/entrypoint.sh"         55 seconds ago      Up 53 seconds       9332/tcp, 19332/tcp, 29332-29333/tcp                   testnet_litecoind_1
e063677205e8        exchangeunion/bitcoind:0.19.0.1   "bitcoind -server -r…"   2 days ago          Up 53 seconds       8332/tcp, 18332/tcp, 28332-28333/tcp                   testnet_bitcoind_1
```

**Comment by kilrau** [comment]
Needs rebase on master.

**Comment by reliveyy** [comment]
@kilrau 

> Entering a wrong path should down all containers (regular down script) + wording fix not existed -> Checking backup location... Failed. Retry? [y/N]

Done.

> ... that it doesn't seem to read-in the backup-dir value from the config ...

Done.

> ... [y/N] ...

Done.

> Allow `~`

Done.

> ... check should not only check if the dir is available ...

Done.

> ... Didn't let me enter the words, immediately threw (path to backup files correct) ...

Not reproduced.

> ... It shouldn't only check if the path is available, it should check if there is a file called xud in the path.

Done.

**Comment by reliveyy** [comment]
> when restoring from a backup folder that contains just an xud database, I still get the following message:
> 
> `Checking files... Looking good. This will restore xud, lndbtc, raiden. Do you wish to continue?`
>
> This is currently a static message, it would be good to only list the components that will actually be restored from the files. And we could also be more specific like saying "the xud database" and "channels from lndbtc".

Good point. `This will restore ...` should reflect the contents of restore folder. @kilrau https://github.com/ExchangeUnion/xud-docker/issues/245#issue-537067056

**Comment by kilrau** [comment]
- [ ] running env with valid backup-dir, then bringing the environment down, changing backup-dir in testnet.conf to something invalid and restarting did detect that backup location is not available but did NOT bring up the prompt to re-enter:
```
Backup location not available.
Backup directory changed from /mnt/hostfs/media/kilrau/BLUE to /mnt/hostfs/media/kilrau/BLU.

                           .___           __  .__   
          ___  _____ __  __| _/     _____/  |_|  |  
          \  \/  /  |  \/ __ |    _/ ___\   __\  |  
           >    <|  |  / /_/ |    \  \___|  | |  |__
          /__/\_ \____/\____ |     \___  >__| |____/
                \/          \/         \/           
--------------------------------------------------------------

testnet > 
```

- [ ] `This will restore ...` should reflect the contents of restore folder. [#245 (comment)](https://github.com/ExchangeUnion/xud-docker/issues/245#issue-537067056)

- [ ] CTRL+C here should gracefully `down environment (it did not):
```
Enter path to backup location: ^C
kilrau@K-Yoga:~$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
ac259c5baf7f        exchangeunion/xud:latest          "/usr/bin/supervisor…"   54 seconds ago      Up 53 seconds       8885/tcp, 8887/tcp, 0.0.0.0:18885-
```

**Comment by reliveyy** [comment]
> Backup location not available.
> Backup directory changed from /mnt/hostfs/media/kilrau/BLUE to /mnt/hostfs/media/kilrau/BLU.

Fixed

> This will restore ... should reflect the contents of restore folder.

Done

> CTRL+C here should gracefully `down environment

WIP

**Comment by kilrau** [comment]
Cases @reliveyy :

1. invalid restore_dir, "continue without?" reply yes -> `You are restoring an xud node key [...]` Entering 24 word SEED.
2. invalid restore_dir, "continue without?" reply no -> `Please paste the path to your XUD backup [...]` Entering path again (b)
3. valid restore_dir, no backup files, "continue without?" reply yes -> `You are restoring an xud node key [...]` Entering 24 word SEED.
4. valid restore_dir, no backup files, "continue without?" reply no -> `Please paste the path to your XUD backup [...]` Entering path again (b)
5. valid restore_dir, has valid backup files,  -> "This will restore x,y,z" reply yes -> `BEWARE` prompt
6. valid restore_dir, has valid backup files,  -> "This will restore x,y,z" reply no -> `1) Create New 2) Restore Existing` selection
7. valid restore_dir, has valid backup files,  -> "This will restore x,y,z" -> "beware prompt" reply yes -> `You are restoring an xud node key [...]` Entering 24 word SEED.
8. valid restore_dir, has valid backup files,  -> "This will restore x,y,z" -> "beware prompt" reply no -> `1) Create New 2) Restore Existing` selection

**Comment by kilrau** [comment]
Path 1 is not working:
```
Please paste the path to your XUD backup to restore your channel balance, your keys and other historical data: /
Checking files... No backup files found. Do you wish to continue WITHOUT restoring channel balance, keys and historical data? [Y/n] 
BEWARE: Restoring your environment will close your existing lnd channels and restore channel balance in your wallet. Do you wish to continue? [Y/n] 

You are restoring an xud node key and underlying wallets. All will be secured by
a single password provided below.
  
Enter your 24 word mnemonic separated by spaces: (node:291) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:291) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:291) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:291) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by sangaman** [comment]
I succeeded with a full flow of creating a node, opening an lnd channel, deleting everything, recovering from my backup directory with seed, and then seeing the recovered channel.

```
testnet > lndbtc-lncli pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "03fd32c61b9310639c25e73cdeccedffa14ead9ab1727ab91cfbb2c111085d1159",
                "channel_point": "36161423e0951943b9cad776538548c793b55517dddafe8bf3ba0ea7bd2baf6c:1",
                "capacity": "30000",
                "local_balance": "0",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0"
            },
            "limbo_balance": "0"
        }
    ]
}
```

**Pull request merged**
