### PR TITLE
Upgrade connext to 6.5.7

### PR DESCRIPTION
**Pull request by erkarl**
Test:
```
bash xud.sh -b chore/upgrade-connext
```

Ensure that you get automatic channels for DAI and USDT and are able to trade these pairs.

### CODE REVIEW

**Comment by raladev** [comment]
- [ ] Got 500 error during XUC/BTC swap.

**Preconditions:**
1. 2 docker simnet setups

**Steps:**
1. sell 300 XUC/BTC 0.0001 1 as Alice
2. buy 300 XUC/BTC mkt

**Result:**
1.
```
19/05/2020 16:01:05.028 [CONNEXT] error: connext server error 500: Internal Server Error
19/05/2020 16:01:05.029 [ORDERBOOK] debug: removed hold of 30000000000 on order e215f160-99e9-11ea-ab5d-157ef7b1657d
19/05/2020 16:01:05.067 [SWAPS] error: could not settle invoice: 7.9 - connext server error
```
2. _I got XUC as taker, and send it as maker, but BTC from taker stucked in pending_htlcs._

**Screens:**
Screenshot from 2020-05-19 19-19-37
Screenshot 2020-05-19 19:05:44
Screenshot 2020-05-19 19:01:45

**Logs:**
taker logs:
[htlcs_xud.log](https://github.com/ExchangeUnion/xud-docker/files/4652007/htlcs_xud.log)
[htlcs_lndbtc.log](https://github.com/ExchangeUnion/xud-docker/files/4652005/htlcs_lndbtc.log)
[htlcs_connext.log](https://github.com/ExchangeUnion/xud-docker/files/4652006/htlcs_connext.log)

maker logs:

<todo>

Note: 
After that I force-close taker's channel and now im waiting for it to be sure that htlcs will be payed to maker.

**Comment by raladev** [comment]
UPD: after some time xud node of taker stops working with following assertion:
```
AssertionError [ERR_ASSERTION]: Can not fail a completed deal.
    at Swaps.<anonymous> (/app/dist/swaps/Swaps.js:797:29)
    at Generator.next (<anonymous>)
    at /app/dist/swaps/Swaps.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/dist/swaps/Swaps.js:4:12)
    at Swaps.failDeal (/app/dist/swaps/Swaps.js:796:97)
    at Swaps.<anonymous> (/app/dist/swaps/Swaps.js:544:32)
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/swaps/Swaps.js:6:65) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
/app/dist/bootstrap.js:13
        throw err;
        ^

AssertionError [ERR_ASSERTION]: Can not fail a completed deal.
    at Swaps.<anonymous> (/app/dist/swaps/Swaps.js:797:29)
    at Generator.next (<anonymous>)
    at /app/dist/swaps/Swaps.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/dist/swaps/Swaps.js:4:12)
    at Swaps.failDeal (/app/dist/swaps/Swaps.js:796:97)
    at Swaps.<anonymous> (/app/dist/swaps/Swaps.js:544:32)
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/swaps/Swaps.js:6:65) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='

```

Logs:
[htlcs_connext_taker_shutdown.log](https://github.com/ExchangeUnion/xud-docker/files/4652307/htlcs_connext_taker_shutdown.log)
[htlcs_lndbtc_taker_shutodwn.log](https://github.com/ExchangeUnion/xud-docker/files/4652308/htlcs_lndbtc_taker_shutodwn.log)
[htlcs_xud_taker_shutdown.log](https://github.com/ExchangeUnion/xud-docker/files/4652309/htlcs_xud_taker_shutdown.log)

**Comment by erkarl** [comment]
> I got XUC as taker, and sent it as maker, but BTC from taker stucked in pending_htlcs.

What happened was that the taker revealed the preimage, but the maker didn't get the memo that it was claimed because on maker side the payment timed out.

Later maker tried to periodically check if the payment was claimed, but was always getting a 500 response code from Connext.

This definitely needs further investigation. Good catch!

1. why the timeout happened and how it can be prevented
2. recovery flow should have "recovered the preimage"

I'm not able to reproduce the issue with my docker environments. Can you try again and see if you're able to reproduce?

**Comment by erkarl** [comment]
> UPD: after some time xud node of taker stops working with following assertion:

Looks like the logs before the crash are incomplete.

@sangaman any idea how this could happen? The taker in this case had a successful swap since they received the payment. Why would it attempt to fail the deal?

**Comment by raladev** [comment]
UPD2:
pending_htlcs returned to the taker after more than 350 blocks. As a result he has XUC (300) and BTC (0.03) that he had to pay for XUC.

pending_htlcs notes:
1. pending_htlcs has two stages of expiration (first was ~80 blocks, second was ~ 280 blocks).
2. channel can not be closed before pending_htlcs expiration.
3. pending_htlcs returns in on-chain way, not in closed channel.
[First stage of expiration](https://user-images.githubusercontent.com/29906866/82429285-4e6fab80-9a94-11ea-9ff7-20cd81436e92.png)
[Second stage of expiration](https://user-images.githubusercontent.com/29906866/82429331-634c3f00-9a94-11ea-9878-794c1f7a10c2.png)
[Listchaintxns + closed channel](https://user-images.githubusercontent.com/29906866/82429414-824ad100-9a94-11ea-8507-7a2106f3ee2a.png)


[Last balances for maker(left) and taker (right)](https://user-images.githubusercontent.com/29906866/82429508-b32b0600-9a94-11ea-8646-9b46971108a7.png)

**Comment by raladev** [comment]
> I'm not able to reproduce the issue with my docker environments. Can you try again and see if you're able to reproduce?

got it again with same order and new clean setup.

Current results:
for now i got:
sell 300 XUC/BTC 0.0001 - fail, 500 error for maker
sell 1 LTC/USDT 700 1 -  success
sell 10 XUC/BTC 0.1 1 - success
openchannel XUC
sell 300 XUC/BTC 0.0001 1 - failed again, 500 error for maker
buy 300 XUC/BTC 0.0001 3 - failed, Swap timeout for Taker
There is definitely something with amount and price

**Comment by erkarl** [comment]
> sell 300 XUC/BTC 0.0001 - fail, 500 error for maker

@raladev upgraded to 6.5.5 and I'm able to do the above successfully now
```
➜  xud git:(master) ✗ ./bin/xucli buy 300 XUC/BTC 0.0001
matched 300 XUC @ 0.0001 with peer MoralAwake order 39226a50-9ae0-11ea-ad7a-c9f295f81e8b, attempting swap...
successfully swapped 300 XUC with peer order 39226a50-9ae0-11ea-ad7a-c9f295f81e8b
```

**Comment by kilrau** [comment]
Looking good, observation connext token balances took significantly longer than ETH, appeared in the order ETH, XUC, USDT, DAI.

```
simnet > getbalance

Balance:
┌──────────┬───────────────┬────────────────────────────┬───────────────────────────────┐
│ Currency │ Total Balance │ Channel Balance (Tradable) │ Wallet Balance (Not Tradable) │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ BTC      │ 2.5           │ 0 (2.5 pending)            │ 0                             │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ DAI      │ 1337          │ 0                          │ 1337                          │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ ETH      │ 14.99979      │ 10                         │ 4.99979                       │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ LTC      │ 5             │ 0 (5 pending)              │ 0                             │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ USDT     │ 1337          │ 0                          │ 1337                          │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ XUC      │ 500           │ 0                          │ 500                           │
└──────────┴───────────────┴────────────────────────────┴───────────────────────────────┘
```

**Comment by raladev** [comment]
- [ ]  Swap timeout for + 500 error for taker with 'sell 0.5 BTC/DAI 2000 1' + 'buy 0.5 BTC/DAI mkt'
[Screenshot 2020-05-21 12:45:07](https://user-images.githubusercontent.com/29906866/82546588-feaae600-9b60-11ea-8a4d-6e1de7ee5fb4.png)

Taker's logs:
[swap_taker_lndbtc.log](https://github.com/ExchangeUnion/xud-docker/files/4661711/swap_taker_lndbtc.log)
[swap_taker_connext.log](https://github.com/ExchangeUnion/xud-docker/files/4661712/swap_taker_connext.log)
[swap_taker_xud.log](https://github.com/ExchangeUnion/xud-docker/files/4661713/swap_taker_xud.log)

Maker's logs:
<TODO>

**Comment by raladev** [comment]
UPD for 6.5.7

- [ ] sell 300 XUC/BTC 0.0001 1 - Swap Time Out for Taker

[Screenshot 2020-05-21 17:19:03](https://user-images.githubusercontent.com/29906866/82568695-df737f00-9b87-11ea-9393-7d3d27a435d5.png)
[Screenshot 2020-05-21 17:18:50](https://user-images.githubusercontent.com/29906866/82568700-e0a4ac00-9b87-11ea-8dfc-e2ae20f69b69.png)

Maker log:
TODO

Taker log:
[again_taker_lndbtc.log](https://github.com/ExchangeUnion/xud-docker/files/4662924/again_taker_lndbtc.log)
[again_taker_connext.log](https://github.com/ExchangeUnion/xud-docker/files/4662926/again_taker_connext.log)
[again_taker_xuc.log](https://github.com/ExchangeUnion/xud-docker/files/4662927/again_taker_xuc.log)

**Comment by raladev** [comment]
Merged, separated issues created for:
https://github.com/ExchangeUnion/xud-docker/pull/464#issuecomment-632115929
https://github.com/ExchangeUnion/xud-docker/pull/464#issuecomment-630986211

**Comment by sangaman** [comment]
> > UPD: after some time xud node of taker stops working with following assertion:
> 
> Looks like the logs before the crash are incomplete.
> 
> @sangaman any idea how this could happen? The taker in this case had a successful swap since they received the payment. Why would it attempt to fail the deal?

Apologies for not seeing sooner. I believe the issue is described (and fixed) here: https://github.com/ExchangeUnion/xud/pull/1571

**Pull request merged**
