### PR TITLE
feat(launcher): do not create conf file if missing

### LINKED ISSUE #263: configuration file issues
- [x] `sample-xud-docker.conf` is not being created in (~/.xud-docker)
- [x] look for existing .conf file on first start and read in if it exists. To state the obvious: Even if config file exists, doesn't mean environment exists (our nodekey.dat detection stays). Goal: make https://docs.exchangeunion.com/start-earning/market-maker-guide#preparation-light-setup work
- [ ] `<network>.conf` & `sample-<network>.conf` are both being created. How it should be: only `sample-<network>.conf` is created containing the latest config options (and is updated regularly). User is using  `cp `sample-mainnet.conf mainnet.conf` to create his own copy and modify. For all 3 networks. 
- [x] update docs with `cp `sample-<network>.conf` instructions (@kilrau )

### PR DESCRIPTION
**Pull request by reliveyy**
This PR will remove the conf file auto creation when it is missing.

Closes #263

### CODE REVIEW

**Comment by kilrau** [comment]
Only this one is left in #263 :
>  <network>.conf & sample-<network>.conf are both being created. How it should be: only sample-<network>.conf is created containing the latest config options (and is updated regularly). User is using cp sample-mainnet.conf mainnet.conf` to create his own copy and modify. For all 3 networks.

This PR should **fully** close it @reliveyy

**Comment by raladev** [comment]
Screenshot from 2020-06-04 17-50-19
failed on backup phase because utils writs backup dir to conf file, but for now we hove no it.

**Comment by reliveyy** [comment]
> failed on backup phase because utils writes backup dir to conf file, but for now we have no it.

Aha. That's a real problem. @kilrau @raladev Should we create the missing conf file before writing backup-dir value in it?

**Comment by raladev** [comment]
current flow for backup dir persist:
1. check config file for backup dir
2. if it does not exist, ask about param specifing
3. persist it to data/xud/.backup-dir-value

**Pull request merged**
